"""
================================================================================
Subtitle Credits-Promotional Content Remover
================================================================================
Author      : Breno Farias da Silva
Created     : 2026-08-23
Description :
    Consumes grouped JSON reports generated by detect.py and removes only the exact
    SRT blocks referenced by those reports.

    The remover does not re-detect content. It verifies each source file SHA-256,
    verifies every target block against its stored SHA-256/index/timestamp/text,
    removes only those exact reported blocks, renumbers all remaining SRT blocks
    sequentially without altering their text/timestamps, validates the resulting
    structure, and publishes changes atomically in place.

    Key features include:
        - Strict reviewed-report-only removal; no independent heuristic decisions,
          rediscovery, target expansion, or removal of occurrences deleted from JSON
        - SHA-256 source-file verification before any modification
        - Exact block identity verification before removal
        - Safe deduplication of grouped report occurrences
        - Sequential SRT renumbering after removals
        - Strict output validation before atomic replacement
        - Exact preservation of remaining subtitle timestamps/text; only target deletion
          and mechanically required sequential index renumbering are published
        - Logger integration and one colored progress bar per input report

Usage:
    1. Run detect.py and review ./Outputs/*-report.json.
    2. Keep SRT files unchanged between detection and removal.
    3. Copy the repository's existing Logger.py beside this script.
    4. Execute:
        $ python remove.py

Outputs:
    - Modified original SRT files when exact report verification succeeds
    - ./Logs/remove.log

TODOs:
    - Add an optional backup mode if historical source preservation is desired.

Dependencies:
    - Python >= 3.10
    - colorama
    - tqdm
    - Local Logger.py from the repository template

Assumptions & Notes:
    - REQUIRE_FILE_HASH_MATCH=True prevents stale-report removal.
    - If a file changed after detection, that file is skipped rather than guessed.
    - Only exact occurrence objects still present in reviewed detector reports are eligible
      for removal. Deleting a finding/occurrence from JSON prevents that block from being removed.
    - Report summary counts/categories are informational and never create removal targets.
    - Non-target subtitle text/timestamps are preserved; the remover does not apply detector logic.
    - Paths stored/read from reports use forward slashes.
"""

import atexit  # For playing a sound when the program finishes
import datetime  # For getting the current date and time
import hashlib  # For verifying source files and exact target blocks
import json  # For reading detector reports
import os  # For running a command in the terminal
import platform  # For getting the operating system name
import re  # For matching and normalizing SRT timestamps
import sys  # For system-specific parameters and functions
from colorama import Style  # For coloring the terminal
from Logger import Logger  # For logging output to both terminal and file
from pathlib import Path  # For handling file paths
from tqdm import tqdm  # For displaying per-report progress bars


# Macros:
class BackgroundColors:  # Colors for the terminal
    CYAN = "\033[96m"  # Cyan
    GREEN = "\033[92m"  # Green
    YELLOW = "\033[93m"  # Yellow
    RED = "\033[91m"  # Red
    BOLD = "\033[1m"  # Bold
    UNDERLINE = "\033[4m"  # Underline
    CLEAR_TERMINAL = "\033[H\033[J"  # Clear the terminal


# Execution Constants:
VERBOSE = False  # Set to True to output verbose messages
INPUT_DIRS = [f"E:/Movies/", f"F:/Documentaries/", f"F:/Movies/", f"F:/Series/", f"G:/Animes/", f"G:/Series/"]  # Input roots whose detector reports are consumed
OUTPUT_DIR = Path("./Outputs")  # Directory containing detector reports
REQUIRE_FILE_HASH_MATCH = True  # Refuse removal if an SRT file changed after detection
REQUIRED_REPORT_SCHEMA_VERSION = 2  # Refuse legacy reports generated by the old false-positive-prone detector
REQUIRED_DETECTION_POLICY = "high_precision_context_v2"  # Require reports from the matching precision-first detector policy
SRT_TEXT_ENCODINGS = ("utf-8-sig", "utf-8", "cp1252", "latin-1")  # Common subtitle encodings


# Logger Setup:
PROGRESS_OUTPUT = sys.stdout  # Preserve original terminal stream so tqdm can update one line in place
logger = Logger(f"./Logs/{Path(__file__).stem}.log", clean=True)  # Create a Logger instance
sys.stdout = logger  # Redirect stdout to the logger
sys.stderr = logger  # Redirect stderr to the logger


# Sound Constants:
SOUND_COMMANDS = {
    "Darwin": "afplay",
    "Linux": "aplay",
    "Windows": "start",
}  # The commands to play a sound for each operating system
SOUND_FILE = "./.assets/Sounds/NotificationSound.wav"  # The path to the sound file


# RUN_FUNCTIONS:
RUN_FUNCTIONS = {
    "Play Sound": True,  # Set to True to play a sound when the program finishes
}


# Functions Definitions:


def verbose_output(true_string="", false_string=""):
    """
    Outputs a message if VERBOSE is True.

    :param true_string: Message shown when VERBOSE is True.
    :param false_string: Optional fallback message.
    :return: None
    """

    if VERBOSE and true_string != "":
        print(true_string)
    elif false_string != "":
        print(false_string)


def verify_filepath_exists(filepath):
    """
    Verify if a file or folder exists.

    :param filepath: Path to verify.
    :return: True when it exists.
    """

    try:
        return isinstance(filepath, str) and bool(filepath.strip()) and os.path.exists(filepath)
    except Exception as exc:
        print(str(exc))
        raise


def to_seconds(obj):
    """
    Convert a time-like object to seconds.

    :param obj: Numeric/timedelta/datetime-like object.
    :return: Float seconds or None.
    """

    if obj is None:
        return None
    if isinstance(obj, (int, float)):
        return float(obj)
    if hasattr(obj, "total_seconds"):
        try:
            return float(obj.total_seconds())
        except Exception:
            pass
    if hasattr(obj, "timestamp"):
        try:
            return float(obj.timestamp())
        except Exception:
            pass
    return None


def calculate_execution_time(start_time, finish_time=None):
    """
    Calculate execution time and return human-readable duration.

    :param start_time: Start object or duration.
    :param finish_time: Optional finish object.
    :return: Human-readable duration.
    """

    if finish_time is None:
        total_seconds = to_seconds(start_time)
        total_seconds = total_seconds if total_seconds is not None else 0.0
    else:
        start_seconds = to_seconds(start_time)
        finish_seconds = to_seconds(finish_time)
        total_seconds = (finish_seconds - start_seconds) if start_seconds is not None and finish_seconds is not None else 0.0

    total_seconds = abs(total_seconds or 0.0)
    days = int(total_seconds // 86400)
    hours = int((total_seconds % 86400) // 3600)
    minutes = int((total_seconds % 3600) // 60)
    seconds = int(total_seconds % 60)

    if days > 0:
        return f"{days}d {hours}h {minutes}m {seconds}s"
    if hours > 0:
        return f"{hours}h {minutes}m {seconds}s"
    if minutes > 0:
        return f"{minutes}m {seconds}s"
    return f"{seconds}s"


def play_sound():
    """
    Play completion sound and skip on Windows.

    :return: None
    """

    current_os = platform.system()

    if current_os == "Windows":
        return

    if verify_filepath_exists(SOUND_FILE) and current_os in SOUND_COMMANDS:
        os.system(f"{SOUND_COMMANDS[current_os]} {SOUND_FILE}")


def file_sha256(filepath: Path) -> str:
    """
    Calculate SHA-256 for one file.

    :param filepath: File to hash.
    :return: Hexadecimal SHA-256 digest.
    """

    digest = hashlib.sha256()

    with filepath.open("rb") as source_file:
        for chunk in iter(lambda: source_file.read(1024 * 1024), b""):
            digest.update(chunk)

    return digest.hexdigest()


def block_sha256(index: int, timestamp: str, text: str) -> str:
    """
    Calculate deterministic SHA-256 identity for one SRT block.

    :param index: Original block index.
    :param timestamp: Original timestamp.
    :param text: Original block text.
    :return: Hexadecimal SHA-256 digest.
    """

    return hashlib.sha256(f"{index}\n{timestamp}\n{text}".encode("utf-8")).hexdigest()


def read_srt_file(filepath: Path) -> str:
    """
    Read one SRT file with common subtitle encodings.

    :param filepath: Source path.
    :return: Decoded text.
    """

    data = filepath.read_bytes()

    if data.startswith((b"\xff\xfe", b"\xfe\xff")):
        return data.decode("utf-16")

    for encoding in SRT_TEXT_ENCODINGS:
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue

    raise UnicodeDecodeError("utf-8", data, 0, 1, "Unable to decode subtitle file")


def parse_srt_blocks(content: str) -> list[dict[str, object]]:
    """
    Parse logical SRT blocks by detecting numeric-index + timestamp headers.

    :param content: Decoded SRT text.
    :return: Ordered parsed block dictionaries.
    """

    normalized_content = content.replace("\r\n", "\n").replace("\r", "\n").strip("\ufeff")
    lines = normalized_content.split("\n")
    blocks = []
    line_index = 0

    while line_index < len(lines):
        current = lines[line_index].strip()

        if current.isdigit() and line_index + 1 < len(lines) and "-->" in lines[line_index + 1]:
            original_index = int(current)
            timestamp = lines[line_index + 1].strip()
            text_start = line_index + 2
            next_index = text_start

            while next_index < len(lines):
                next_line = lines[next_index].strip()
                if next_line.isdigit() and next_index + 1 < len(lines) and "-->" in lines[next_index + 1]:
                    break
                next_index += 1

            text_lines = lines[text_start:next_index]

            while text_lines and not text_lines[0].strip():
                text_lines.pop(0)
            while text_lines and not text_lines[-1].strip():
                text_lines.pop()

            blocks.append(
                {
                    "block_number": len(blocks) + 1,
                    "original_index": original_index,
                    "timestamp": timestamp,
                    "text": "\n".join(text_lines),
                }
            )
            line_index = next_index
            continue

        line_index += 1

    return blocks


def serialize_and_validate_blocks(blocks: list[dict[str, object]]) -> str:
    """
    Renumber remaining blocks sequentially while preserving their text/timestamps exactly.

    No timestamp normalization or unrelated subtitle cleanup is performed here.
    The only intentional changes are removal of exact report targets and the
    sequential index renumbering mechanically required after those deletions.

    :param blocks: Remaining SRT blocks after exact report-driven removals.
    :return: Serialized SRT text.
    """

    serialized_blocks = []

    for new_index, block in enumerate(blocks, start=1):
        text = str(block["text"]).strip("\n")
        timestamp = str(block["timestamp"])

        if not text.strip():
            raise ValueError(f"Cannot serialize empty subtitle block originally indexed {block['original_index']}")

        if "-->" not in timestamp:
            raise ValueError(
                f"Cannot preserve malformed timestamp for untouched block originally indexed "
                f"{block['original_index']}: {timestamp}"
            )

        serialized_blocks.append(f"{new_index}\n{timestamp}\n{text}")

    serialized = "\n\n".join(serialized_blocks) + ("\n" if serialized_blocks else "")
    reparsed = parse_srt_blocks(serialized)

    if len(reparsed) != len(blocks):
        raise ValueError("Serialized SRT validation failed: block count changed unexpectedly")

    for expected_index, (original_block, reparsed_block) in enumerate(zip(blocks, reparsed), start=1):
        if int(reparsed_block["original_index"]) != expected_index:
            raise ValueError(f"Serialized SRT validation failed at index {expected_index}")

        if str(reparsed_block["timestamp"]) != str(original_block["timestamp"]):
            raise ValueError(
                f"Serialized SRT validation changed timestamp of untouched block "
                f"{original_block['original_index']}"
            )

        if str(reparsed_block["text"]) != str(original_block["text"]).strip("\n"):
            raise ValueError(
                f"Serialized SRT validation changed text of untouched block "
                f"{original_block['original_index']}"
            )

    return serialized


def atomic_write_text(filepath: Path, content: str) -> None:
    """
    Atomically replace a text file.

    :param filepath: Destination path.
    :param content: UTF-8 content.
    :return: None
    """

    temporary_filepath = filepath.with_name(f".{filepath.name}.{os.getpid()}.tmp")

    try:
        with open(temporary_filepath, "w", encoding="utf-8", newline="\n") as temporary_file:
            temporary_file.write(content)
        os.replace(temporary_filepath, filepath)
    finally:
        if temporary_filepath.exists():
            temporary_filepath.unlink()


def build_report_filename_prefix(configured_input_dir: str) -> str:
    """
    Build Windows-safe report filename prefix.

    :param configured_input_dir: Configured input root.
    :return: Safe report prefix.
    """

    normalized = re.sub(r"[\\/]+", "-", str(configured_input_dir).strip())
    normalized = re.sub(r'[<>:"|?*]+', "-", normalized)
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-. ")
    return normalized or "input"


def build_report_path(configured_input_dir: str) -> Path:
    """
    Build detector report path for one configured input root.

    :param configured_input_dir: Configured input root.
    :return: Report path.
    """

    return OUTPUT_DIR / f"{build_report_filename_prefix(configured_input_dir)}-report.json"


def load_report(report_path: Path) -> dict[str, object]:
    """
    Load and minimally validate one detector report.

    :param report_path: JSON report path.
    :return: Parsed report dictionary.
    """

    with report_path.open("r", encoding="utf-8") as report_file:
        report = json.load(report_file)

    if not isinstance(report, dict) or not isinstance(report.get("findings"), list):
        raise ValueError(f"Invalid detector report structure: {report_path}")

    if int(report.get("schema_version", -1)) != REQUIRED_REPORT_SCHEMA_VERSION:
        raise ValueError(
            f"Refusing legacy detector report without schema version "
            f"{REQUIRED_REPORT_SCHEMA_VERSION}: {report_path}. Regenerate it with the updated detect.py."
        )

    if str(report.get("detection_policy", "")) != REQUIRED_DETECTION_POLICY:
        raise ValueError(
            f"Refusing detector report from an unsupported detection policy: {report_path}. "
            f"Expected {REQUIRED_DETECTION_POLICY!r}."
        )

    report_input_dir = str(report.get("input_dir", "")).replace("\\", "/").rstrip("/")

    if not report_input_dir:
        raise ValueError(f"Detector report is missing input_dir: {report_path}")

    return report


def flatten_report_targets(report: dict[str, object]) -> dict[str, list[dict[str, object]]]:
    """
    Flatten ONLY exact occurrence objects still present in the reviewed JSON report.

    Removing an occurrence or entire finding from the JSON before running this
    script guarantees that deleted report entry creates no removal target.
    Summary counts, finding strings/categories, and detector heuristics are never
    used to reconstruct or infer omitted targets.

    :param report: Reviewed detector report.
    :return: Mapping from exact reported file paths to exact unique occurrence targets.
    """

    targets_by_file = {}
    seen_targets = set()
    required_fields = {
        "file_path",
        "file_sha256",
        "block_sha256",
        "original_index",
        "timestamp",
        "text",
    }

    findings = report.get("findings", [])
    report_input_dir = str(report.get("input_dir", "")).replace("\\", "/").rstrip("/") + "/"

    if not isinstance(findings, list):
        raise ValueError("Detector report 'findings' must be a list")

    for finding in findings:
        if not isinstance(finding, dict):
            continue

        occurrences = finding.get("occurrences", [])

        if not isinstance(occurrences, list):
            continue

        for occurrence in occurrences:
            if not isinstance(occurrence, dict):
                continue

            if not required_fields.issubset(occurrence):
                continue  # Incomplete/manual report rows are never guessed or expanded

            file_path = str(occurrence["file_path"]).strip().replace("\\", "/")
            block_hash = str(occurrence["block_sha256"]).strip()
            target_key = (file_path.casefold(), block_hash)

            if not file_path or not block_hash or target_key in seen_targets:
                continue

            if not file_path.casefold().startswith(report_input_dir.casefold()):
                continue  # Never let a reviewed report target files outside its own configured input root

            seen_targets.add(target_key)
            targets_by_file.setdefault(file_path, []).append(occurrence)

    return targets_by_file


def verify_target_block(block: dict[str, object], target: dict[str, object]) -> bool:
    """
    Verify one parsed block matches one report target exactly.

    :param block: Current parsed SRT block.
    :param target: Stored detector occurrence.
    :return: True when exact identity matches.
    """

    current_hash = block_sha256(
        int(block["original_index"]),
        str(block["timestamp"]),
        str(block["text"]),
    )

    return (
        current_hash == str(target.get("block_sha256", ""))
        and int(block["original_index"]) == int(target.get("original_index", -1))
        and str(block["timestamp"]) == str(target.get("timestamp", ""))
        and str(block["text"]) == str(target.get("text", ""))
    )


def remove_reported_blocks(filepath: Path, targets: list[dict[str, object]]) -> tuple[int, str]:
    """
    Remove exact report targets from one SRT file and publish validated result.

    :param filepath: Source SRT file.
    :param targets: Exact detector occurrences for this file.
    :return: Number of removed blocks and status string.
    """

    if not targets:
        return 0, "no_report_targets"  # Never touch a file without an exact occurrence still present in the reviewed report

    if not filepath.exists() or not filepath.is_file():
        return 0, "missing_file"

    expected_file_hashes = {str(target.get("file_sha256", "")) for target in targets if target.get("file_sha256")}
    current_file_hash = file_sha256(filepath)

    if REQUIRE_FILE_HASH_MATCH and expected_file_hashes != {current_file_hash}:
        return 0, "file_hash_mismatch"

    content = read_srt_file(filepath)
    blocks = parse_srt_blocks(content)
    target_by_hash = {str(target["block_sha256"]): target for target in targets}
    removed_hashes = set()
    remaining_blocks = []

    for block in blocks:
        current_hash = block_sha256(
            int(block["original_index"]),
            str(block["timestamp"]),
            str(block["text"]),
        )
        target = target_by_hash.get(current_hash)

        if target is not None and verify_target_block(block, target):
            removed_hashes.add(current_hash)
            continue

        remaining_blocks.append(block)

    expected_hashes = set(target_by_hash)

    if removed_hashes != expected_hashes:
        return 0, "target_block_mismatch"

    cleaned_content = serialize_and_validate_blocks(remaining_blocks)
    atomic_write_text(filepath, cleaned_content)
    return len(removed_hashes), "removed"


def main():
    """
    Main function.

    :return: None
    """

    print(
        f"{BackgroundColors.CLEAR_TERMINAL}{BackgroundColors.BOLD}{BackgroundColors.GREEN}Welcome to the {BackgroundColors.CYAN}Subtitle Credits-Promotional Content Remover{BackgroundColors.GREEN} program!{Style.RESET_ALL}",
        end="\n\n",
    )

    start_time = datetime.datetime.now()
    files_modified = 0
    blocks_removed = 0
    files_skipped = 0
    reports_processed = 0

    for configured_input_dir in INPUT_DIRS:
        report_path = build_report_path(str(configured_input_dir))

        if not report_path.exists():
            print(f"{BackgroundColors.YELLOW}Report not found: {BackgroundColors.CYAN}{report_path.as_posix()}{Style.RESET_ALL}")
            continue

        report = load_report(report_path)
        targets_by_file = flatten_report_targets(report)
        reports_processed += 1
        sorted_files = sorted(targets_by_file, key=str.casefold)

        if not sorted_files:
            print(
                f"{BackgroundColors.GREEN}No reviewed removal targets: "
                f"{BackgroundColors.CYAN}{report_path.as_posix()}{Style.RESET_ALL}"
            )
            continue

        with tqdm(
            sorted_files,
            total=len(sorted_files),
            file=PROGRESS_OUTPUT,
            desc=f"{BackgroundColors.GREEN}Removing {BackgroundColors.CYAN}{report_path.name}{Style.RESET_ALL}",
            unit="file",
            dynamic_ncols=True,
            leave=True,
            colour="green",
            bar_format="{desc}: {percentage:3.0f}%|{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}] {postfix}",
        ) as progress_bar:
            for reported_file_path in progress_bar:
                filepath = Path(reported_file_path)
                progress_bar.set_postfix_str(
                    f"{BackgroundColors.GREEN}File: {BackgroundColors.CYAN}{filepath.as_posix()}{Style.RESET_ALL}",
                    refresh=True,
                )

                try:
                    removed_count, status = remove_reported_blocks(filepath, targets_by_file[reported_file_path])

                    if status == "removed":
                        files_modified += 1
                        blocks_removed += removed_count
                    else:
                        files_skipped += 1
                        tqdm.write(
                            f"{BackgroundColors.YELLOW}Skipped: {BackgroundColors.CYAN}{filepath.as_posix()}"
                            f"{BackgroundColors.YELLOW} - {status}{Style.RESET_ALL}",
                            file=PROGRESS_OUTPUT,
                        )
                except Exception as exc:
                    files_skipped += 1
                    tqdm.write(
                        f"{BackgroundColors.RED}Failed: {BackgroundColors.CYAN}{filepath.as_posix()}"
                        f"{BackgroundColors.RED} - {exc}{Style.RESET_ALL}",
                        file=PROGRESS_OUTPUT,
                    )

    finish_time = datetime.datetime.now()

    print(
        f"{BackgroundColors.GREEN}Summary:{Style.RESET_ALL}\n"
        f"{BackgroundColors.GREEN}Reports processed: {BackgroundColors.CYAN}{reports_processed}{Style.RESET_ALL}\n"
        f"{BackgroundColors.GREEN}Files modified: {BackgroundColors.CYAN}{files_modified}{Style.RESET_ALL}\n"
        f"{BackgroundColors.GREEN}Blocks removed: {BackgroundColors.CYAN}{blocks_removed}{Style.RESET_ALL}\n"
        f"{BackgroundColors.GREEN}Files skipped/failed: {BackgroundColors.CYAN}{files_skipped}{Style.RESET_ALL}"
    )

    print(
        f"{BackgroundColors.GREEN}Start time: {BackgroundColors.CYAN}{start_time.strftime('%d/%m/%Y - %H:%M:%S')}\n"
        f"{BackgroundColors.GREEN}Finish time: {BackgroundColors.CYAN}{finish_time.strftime('%d/%m/%Y - %H:%M:%S')}\n"
        f"{BackgroundColors.GREEN}Execution time: {BackgroundColors.CYAN}{calculate_execution_time(start_time, finish_time)}{Style.RESET_ALL}"
    )

    print(f"{BackgroundColors.BOLD}{BackgroundColors.GREEN}Program finished.{Style.RESET_ALL}")

    (
        atexit.register(play_sound) if RUN_FUNCTIONS["Play Sound"] else None
    )


if __name__ == "__main__":
    """
    Standard boilerplate that calls main().

    :return: None
    """

    main()
