"""
================================================================================
Report Track Metadata Corrector
================================================================================
Author      : Breno Farias da Silva
Created     : 2026-08-27
Description :
    Applies report-driven audio and embedded subtitle metadata fixes to Matroska
    files using mkvpropedit only. The workflow consumes JSON reports generated by
    main.py, maps report rows to current streams by verified report order, and
    refuses unsupported containers instead of remuxing or re-encoding media.
"""

from __future__ import annotations  # Enable modern annotations on supported Python versions.

import argparse  # Parse command-line arguments.
import datetime  # Track execution timestamps.
import hashlib  # Build stable lock names from media paths.
import json  # Read report JSON and probe metadata.
import os  # Read process and platform details.
from dataclasses import dataclass, field  # Define typed workflow records.
from pathlib import Path  # Represent filesystem paths.
import re  # Parse report track display text.
import shutil  # Locate required command-line tools.
import subprocess  # Run ffprobe, mkvmerge, and mkvpropedit safely.
import sys  # Return CLI exit statuses.
import tempfile  # Store cross-process lock files outside media directories.
import time  # Retry Windows byte locks.
import unicodedata  # Normalize accents for language matching.
from typing import Any, TextIO  # Type dynamic JSON and lock streams.

from colorama import Style  # Reuse target project terminal reset behavior.
from tqdm import tqdm  # Render colored progress bars for file processing.


class BackgroundColors:  # Store terminal color escape constants.
    CYAN = "\033[96m"  # Store cyan terminal color.
    GREEN = "\033[92m"  # Store green terminal color.
    YELLOW = "\033[93m"  # Store yellow terminal color.
    RED = "\033[91m"  # Store red terminal color.
    BOLD = "\033[1m"  # Store bold terminal style.
    CLEAR_TERMINAL = "\033[H\033[J"  # Store terminal-clear escape sequence.


SCRIPT_DIRECTORY = Path(__file__).resolve().parent  # Resolve script directory.
REPORTS_DIRECTORY = SCRIPT_DIRECTORY / "Reports"  # Resolve default reports directory.
SUPPORTED_MKV_EXTENSIONS = (".mkv", ".mk3d")  # Limit mutations to Matroska containers supported by mkvpropedit.
UNSUPPORTED_MUTATION_EXTENSIONS = (".mp4", ".avi", ".mov")  # Name known report containers that are intentionally skipped.
MEDIA_LOCK_DIRECTORY = Path(tempfile.gettempdir()) / "report_track_metadata_corrector_locks"  # Store per-media edit locks.
LOCK_BYTE_COUNT = 1  # Lock one byte consistently across platforms.
LOCK_RETRY_SECONDS = 0.1  # Pause briefly between Windows lock attempts.
REPORT_MOVIES_KEY_PATTERN = re.compile(r"^Movies \(\d+\)$")  # Match counted movie-list keys from main.py reports.
DEFAULT_SUFFIX_PATTERN = re.compile(r"\s*\(Default\)\s*$", re.IGNORECASE)  # Match default marker appended by main.py.
PAREN_LANGUAGE_PATTERN = re.compile(r"\((?P<value>[^()]+)\)")  # Match parenthesized language codes in report strings.
INTERNAL_SUBTITLE_PATTERN = re.compile(r"^Internal:\s*(?P<body>.*)$", re.IGNORECASE)  # Match internal subtitle report rows.
COMMENTARY_MARKERS = {"commentary", "comentario", "comentário", "description", "descriptive"}  # Store secondary-audio markers.
PT_BR_INDICATORS = {"brazilian", "brasil", "brazil", "brasileiro", "ptbr", "pob", "pb", "bra"}  # Store explicit Brazilian Portuguese indicators.
FFMPEG_ERROR_FLAGS = ("-v", "error", "-xerror")  # Configure FFmpeg to fail on media errors.
FFMPEG_NULL_OUTPUT = ("-map", "0:v?", "-map", "0:a?", "-f", "null", "-")  # Decode audio and video without writing media.


LANGUAGE_ALIASES = {  # Store canonical language aliases adapted from MKV-Tracks-Metadata-Manager.
    "English": ("en", "eng", "english", "ingles", "inglês"),  # Store English aliases.
    "Brazilian Portuguese": ("pt-br", "pt br", "pob", "brazilian portuguese", "portuguese brazil", "portuguese brasil", "portugues brasil", "português brasil", "ptbr", "pb"),  # Store Brazilian Portuguese aliases.
    "Portuguese": ("pt", "pt-pt", "pt pt", "por", "portuguese", "portuguese portugal", "european portuguese", "portugues", "português", "portugues portugal", "português portugal"),  # Store Portuguese aliases.
    "Arabic": ("ar", "ara", "arabic", "árabe", "arabe"),  # Store Arabic aliases.
    "Spanish": ("es", "spa", "spanish", "espanol", "español", "castellano", "latam"),  # Store Spanish aliases.
    "Czech": ("cs", "ces", "cze", "czech", "čeština", "cestina", "checo"),  # Store Czech aliases.
    "Danish": ("da", "dan", "danish", "dinamarques", "dinamarquês"),  # Store Danish aliases.
    "French": ("fr", "fre", "fra", "french", "francais", "français"),  # Store French aliases.
    "German": ("de", "ger", "deu", "german", "deutsch"),  # Store German aliases.
    "Greek": ("el", "ell", "gre", "greek", "grego", "ελληνικά"),  # Store Greek aliases.
    "Finnish": ("fi", "fin", "finnish", "finlandes", "finlandês"),  # Store Finnish aliases.
    "Hebrew": ("he", "heb", "hebrew", "hebraico", "עברית"),  # Store Hebrew aliases.
    "Hungarian": ("hu", "hun", "hungarian", "hungaro", "húngaro", "magyar"),  # Store Hungarian aliases.
    "Indonesian": ("id", "ind", "indonesian", "indonesio", "indonésio", "bahasa indonesia"),  # Store Indonesian aliases.
    "Italian": ("it", "ita", "italian", "italiano"),  # Store Italian aliases.
    "Japanese": ("ja", "jpn", "japanese", "nihongo"),  # Store Japanese aliases.
    "Korean": ("ko", "kor", "korean"),  # Store Korean aliases.
    "Chinese": ("zh", "zh-cn", "zh-tw", "zh-hans", "zh-hant", "zho", "chi", "chinese", "mandarin", "cantonese"),  # Store Chinese aliases.
    "Dutch": ("nl", "nld", "dut", "dutch", "holandes", "holandês", "nederlands"),  # Store Dutch aliases.
    "Norwegian": ("no", "nor", "nob", "norwegian", "noruegues", "norueguês", "bokmal", "bokmål"),  # Store Norwegian aliases.
    "Polish": ("pl", "pol", "polish", "polones", "polonês"),  # Store Polish aliases.
    "Romanian": ("ro", "ron", "rum", "romanian", "romeno", "română", "romana"),  # Store Romanian aliases.
    "Russian": ("ru", "rus", "russian"),  # Store Russian aliases.
    "Swedish": ("sv", "swe", "swedish", "sueco"),  # Store Swedish aliases.
    "Thai": ("th", "tha", "thai", "tailandes", "tailandês"),  # Store Thai aliases.
    "Turkish": ("tr", "tur", "turkish", "turco"),  # Store Turkish aliases.
    "Vietnamese": ("vi", "vie", "vietnamese", "vietnamita", "tiếng việt"),  # Store Vietnamese aliases.
    "Hindi": ("hi", "hin", "hindi"),  # Store Hindi aliases.
}  # Close canonical language alias mapping.

LANGUAGE_CODES = {  # Store Matroska language codes for canonical names.
    "English": "eng",  # Store English code.
    "Brazilian Portuguese": "por",  # Store Brazilian Portuguese code.
    "Portuguese": "por",  # Store Portuguese code.
    "Arabic": "ara",  # Store Arabic code.
    "Spanish": "spa",  # Store Spanish code.
    "Czech": "cze",  # Store Czech code.
    "Danish": "dan",  # Store Danish code.
    "French": "fre",  # Store French code.
    "German": "ger",  # Store German code.
    "Greek": "gre",  # Store Greek code.
    "Finnish": "fin",  # Store Finnish code.
    "Hebrew": "heb",  # Store Hebrew code.
    "Hungarian": "hun",  # Store Hungarian code.
    "Indonesian": "ind",  # Store Indonesian code.
    "Italian": "ita",  # Store Italian code.
    "Japanese": "jpn",  # Store Japanese code.
    "Korean": "kor",  # Store Korean code.
    "Chinese": "chi",  # Store Chinese code.
    "Dutch": "dut",  # Store Dutch code.
    "Norwegian": "nor",  # Store Norwegian code.
    "Polish": "pol",  # Store Polish code.
    "Romanian": "rum",  # Store Romanian code.
    "Russian": "rus",  # Store Russian code.
    "Swedish": "swe",  # Store Swedish code.
    "Thai": "tha",  # Store Thai code.
    "Turkish": "tur",  # Store Turkish code.
    "Vietnamese": "vie",  # Store Vietnamese code.
    "Hindi": "hin",  # Store Hindi code.
}  # Close Matroska language code mapping.

LANGUAGE_IETF_CODES = {  # Store BCP-47 language codes for precise Matroska metadata.
    "English": "en",  # Store English BCP-47 code.
    "Brazilian Portuguese": "pt-BR",  # Store Brazilian Portuguese BCP-47 code.
    "Portuguese": "pt-PT",  # Store Portugal Portuguese BCP-47 code.
    "Arabic": "ar",  # Store Arabic BCP-47 code.
    "Spanish": "es",  # Store Spanish BCP-47 code.
    "Czech": "cs",  # Store Czech BCP-47 code.
    "Danish": "da",  # Store Danish BCP-47 code.
    "French": "fr",  # Store French BCP-47 code.
    "German": "de",  # Store German BCP-47 code.
    "Greek": "el",  # Store Greek BCP-47 code.
    "Finnish": "fi",  # Store Finnish BCP-47 code.
    "Hebrew": "he",  # Store Hebrew BCP-47 code.
    "Hungarian": "hu",  # Store Hungarian BCP-47 code.
    "Indonesian": "id",  # Store Indonesian BCP-47 code.
    "Italian": "it",  # Store Italian BCP-47 code.
    "Japanese": "ja",  # Store Japanese BCP-47 code.
    "Korean": "ko",  # Store Korean BCP-47 code.
    "Chinese": "zh",  # Store Chinese BCP-47 code.
    "Dutch": "nl",  # Store Dutch BCP-47 code.
    "Norwegian": "no",  # Store Norwegian BCP-47 code.
    "Polish": "pl",  # Store Polish BCP-47 code.
    "Romanian": "ro",  # Store Romanian BCP-47 code.
    "Russian": "ru",  # Store Russian BCP-47 code.
    "Swedish": "sv",  # Store Swedish BCP-47 code.
    "Thai": "th",  # Store Thai BCP-47 code.
    "Turkish": "tr",  # Store Turkish BCP-47 code.
    "Vietnamese": "vi",  # Store Vietnamese BCP-47 code.
    "Hindi": "hi",  # Store Hindi BCP-47 code.
}  # Close BCP-47 language code mapping.


@dataclass(frozen=True)  # Generate immutable lock record methods.
class FileLock:  # Store an acquired file lock.
    path: Path  # Store lock file path.
    stream: TextIO  # Store lock-owning stream.


@dataclass(frozen=True)  # Generate immutable report audio record methods.
class ReportAudioTrack:  # Store intended report audio metadata.
    position: int  # Store zero-based audio position.
    raw_text: str  # Store raw report text.
    language: str  # Store canonical language.
    language_code: str  # Store target Matroska language code.
    language_ietf: str  # Store target BCP-47 language code.
    target_name: str  # Store target track name.
    report_default: bool  # Store report default marker state.
    secondary: bool  # Store likely secondary-audio marker state.


@dataclass(frozen=True)  # Generate immutable report subtitle record methods.
class ReportSubtitleTrack:  # Store intended report subtitle metadata.
    position: int  # Store zero-based subtitle position.
    raw_text: str  # Store raw report text.
    language: str  # Store canonical language.
    language_code: str  # Store target Matroska language code.
    language_ietf: str  # Store target BCP-47 language code.
    target_name: str  # Store target track name.
    internal: bool  # Store whether row targets an internal stream.


@dataclass(frozen=True)  # Generate immutable movie report record methods.
class MovieReportEntry:  # Store one movie entry from one report.
    report_path: Path  # Store source report path.
    input_dir: Path  # Store report input root for relative progress text.
    full_path: Path  # Store media path from report.
    audio_tracks: list[ReportAudioTrack]  # Store intended audio rows.
    subtitle_tracks: list[ReportSubtitleTrack]  # Store intended subtitle rows.


@dataclass(frozen=True)  # Generate immutable stream snapshot record methods.
class StreamSnapshot:  # Store current stream metadata.
    position: int  # Store zero-based type-specific position.
    stream_index: int | None  # Store container stream index.
    track_uid: int | None  # Store Matroska Track UID.
    codec_name: str  # Store codec name.
    codec_type: str  # Store codec type.
    language_code: str  # Store current language code.
    language_ietf: str  # Store current BCP-47 language code.
    name: str  # Store current track name.
    default: bool  # Store current default flag.
    forced: bool  # Store current forced flag.


@dataclass(frozen=True)  # Generate immutable track edit record methods.
class TrackEdit:  # Store one mkvpropedit track edit.
    selector: str  # Store mkvpropedit track selector.
    current_name: str  # Store current track name.
    new_name: str | None = None  # Store target name when needed.
    language_code: str | None = None  # Store target language code when needed.
    language_ietf: str | None = None  # Store target BCP-47 language code when needed.
    default_flag: bool | None = None  # Store target default flag when needed.


@dataclass(frozen=True)  # Generate immutable file plan record methods.
class PlannedFileEdit:  # Store a validated file edit plan.
    movie: MovieReportEntry  # Store source report movie entry.
    before_audio: list[StreamSnapshot]  # Store pre-edit audio snapshot.
    before_subtitles: list[StreamSnapshot]  # Store pre-edit subtitle snapshot.
    edits: list[TrackEdit]  # Store requested track edits.
    default_audio_position: int | None  # Store intended default audio position.
    warnings: list[str] = field(default_factory=list)  # Store planning warnings.


@dataclass(frozen=True)  # Generate immutable mkvpropedit result record methods.
class EditExecutionResult:  # Store one mkvpropedit execution result.
    success: bool  # Store command success state.
    warning: bool  # Store MKVToolNix warning state.
    setter_count: int  # Store requested setter count.
    details: str  # Store command diagnostics.


@dataclass  # Generate mutable workflow summary record methods.
class WorkflowSummary:  # Store workflow counters and messages.
    reports: int = 0  # Store loaded report count.
    files: int = 0  # Store processed file count.
    planned_files: int = 0  # Store file count with planned changes.
    changed_files: int = 0  # Store successfully changed file count.
    planned_edits: int = 0  # Store requested setter count.
    warnings: int = 0  # Store warning count.
    skipped: int = 0  # Store skipped item count.
    failed: int = 0  # Store failed item count.
    messages: list[str] = field(default_factory=list)  # Store workflow messages.


def normalize_text(value: object) -> str:
    """
    Normalize text for reliable metadata language matching.

    :param value: Raw metadata value.
    :return: Normalized comparable text.
    """

    text = "" if value is None else str(value)  # Convert missing values to empty text.
    text = text.lower()  # Convert text to lowercase.
    text = unicodedata.normalize("NFKD", text)  # Split accents from base characters.
    text = "".join(character for character in text if not unicodedata.combining(character))  # Remove accent marks.
    text = re.sub(r"\b\d+(\.\d+)?\b", " ", text)  # Remove isolated numeric quality markers.
    text = re.sub(r"[\(\)\[\]\{\}_\-\.]+", " ", text)  # Replace separators with spaces.
    text = re.sub(r"\s+", " ", text).strip()  # Collapse whitespace.
    return text  # Return normalized text.


def build_normalized_aliases() -> dict[str, list[str]]:
    """
    Build normalized aliases for configured language names.

    :return: Mapping from canonical language to normalized aliases.
    """

    normalized_aliases: dict[str, list[str]] = {}  # Store normalized aliases by language.
    for language_name, aliases in LANGUAGE_ALIASES.items():  # Iterate configured language groups.
        values = [language_name, *aliases]  # Include canonical name as alias.
        normalized_aliases[language_name] = sorted({normalize_text(value) for value in values if normalize_text(value)})  # Store deterministic aliases.
    return normalized_aliases  # Return normalized alias mapping.


def normalize_language_value(value: object) -> str:
    """
    Resolve one metadata value into a canonical language name.

    :param value: Raw metadata value.
    :return: Canonical language name or empty text.
    """

    normalized_value = normalize_text(value)  # Normalize raw value.
    if normalized_value == "" or normalized_value in {"und", "undefined", "unknown", "mis", "mul"}:  # Reject unknown metadata markers.
        return ""  # Return unknown language.

    compact_value = normalized_value.replace(" ", "")  # Build compact value for region tags.
    if compact_value in {"ptbr", "pob", "pb", "bra"} or "ptbr" in compact_value or "pt br" in normalized_value or any(indicator in normalized_value.split() for indicator in PT_BR_INDICATORS):  # Detect explicit Brazilian Portuguese markers.
        return "Brazilian Portuguese"  # Return canonical Brazilian Portuguese label.

    aliases = build_normalized_aliases()  # Build alias mapping.
    for language_name, language_aliases in aliases.items():  # Prefer exact alias matches.
        if normalized_value in language_aliases:  # Validate exact normalized match.
            return language_name  # Return canonical language.

    for language_name, language_aliases in aliases.items():  # Try token matches for longer metadata strings.
        for alias in language_aliases:  # Iterate aliases.
            if len(alias) < 3:  # Avoid unsafe tiny fuzzy aliases.
                continue  # Skip tiny alias.
            if alias in normalized_value.split():  # Validate full-token alias.
                return language_name  # Return canonical language.

    for language_name, language_aliases in aliases.items():  # Try conservative substring matches.
        for alias in language_aliases:  # Iterate aliases.
            if len(alias) < 4:  # Avoid unsafe short substring matches.
                continue  # Skip short alias.
            if alias in normalized_value:  # Validate substring alias.
                return language_name  # Return canonical language.

    return ""  # Return unknown language.


def normalize_subtitle_language_value(value: object) -> str:
    """
    Resolve one subtitle metadata value into a canonical language name.

    :param value: Raw metadata value.
    :return: Canonical subtitle language name or empty text.
    """

    normalized_value = normalize_text(value)  # Normalize raw value before subtitle-specific handling.
    compact_value = normalized_value.replace(" ", "")  # Build compact value for region tags.
    if compact_value in {"ptbr", "pob", "pb", "bra"} or "ptbr" in compact_value or "pt br" in normalized_value or any(indicator in normalized_value.split() for indicator in PT_BR_INDICATORS):  # Detect explicit Brazilian Portuguese.
        return "Brazilian Portuguese"  # Return canonical Brazilian Portuguese label.
    if normalized_value in {"pt pt", "ptpt", "portuguese portugal", "european portuguese", "portugues portugal"}:  # Detect explicit Portugal Portuguese.
        return "Portuguese"  # Return canonical Portuguese label.
    return normalize_language_value(value)  # Return shared normalization result.


def find_executable(command_name: str) -> str | None:
    """
    Find an executable on PATH or common MKVToolNix Windows paths.

    :param command_name: Executable name.
    :return: Executable path or None.
    """

    path_result = shutil.which(command_name)  # Search PATH first.
    if path_result is not None:  # Validate PATH lookup result.
        return path_result  # Return PATH executable.

    if os.name == "nt" and command_name.lower() in {"mkvpropedit", "mkvmerge", "ffprobe", "ffmpeg"}:  # Use known Windows install roots for media tools.
        executable_name = f"{command_name}.exe"  # Build Windows executable name.
        program_dirs = [os.environ.get("ProgramFiles"), os.environ.get("ProgramFiles(x86)")]  # Read standard program directories.
        for program_dir in program_dirs:  # Iterate program directories.
            if not program_dir:  # Skip missing environment values.
                continue  # Continue with next install root.
            mkv_candidate = Path(program_dir) / "MKVToolNix" / executable_name  # Build MKVToolNix candidate path.
            if mkv_candidate.exists():  # Validate MKVToolNix candidate.
                return str(mkv_candidate)  # Return discovered executable.

    return None  # Return missing executable.


def acquire_file_lock(lock_path: Path, owner_text: str) -> FileLock:
    """
    Acquire one exclusive file lock and return its handle.

    :param lock_path: Lock file path.
    :param owner_text: Diagnostic owner text.
    :return: Acquired file lock handle.
    """

    lock_path.parent.mkdir(parents=True, exist_ok=True)  # Ensure lock directory exists.
    stream = lock_path.open("a+", encoding="utf-8")  # Open coordination file.
    try:  # Acquire operating-system lock before writing owner data.
        if os.name == "nt":  # Use Windows byte-range locking on Windows.
            import msvcrt  # Import Windows lock support only on Windows.
            while True:  # Retry until lock becomes available.
                try:  # Attempt non-blocking Windows lock acquisition.
                    stream.seek(0)  # Move to selected byte.
                    msvcrt.locking(stream.fileno(), msvcrt.LK_NBLCK, LOCK_BYTE_COUNT)  # Acquire one-byte exclusive lock.
                    break  # Stop retrying after lock acquisition.
                except OSError:  # Handle lock owned by another process.
                    time.sleep(LOCK_RETRY_SECONDS)  # Wait before retrying.
        else:  # Use POSIX flock elsewhere.
            import fcntl  # Import POSIX lock support only on POSIX.
            fcntl.flock(stream.fileno(), fcntl.LOCK_EX)  # Acquire exclusive POSIX lock.

        stream.seek(0)  # Move to beginning before diagnostics write.
        stream.truncate(0)  # Remove previous diagnostics while owning lock.
        stream.write(f"{owner_text.rstrip()}\n")  # Write current owner diagnostics.
        stream.flush()  # Flush owner diagnostics.
        return FileLock(lock_path, stream)  # Return handle-owned lock.
    except Exception:  # Close stream after failed lock acquisition.
        stream.close()  # Close stream to release partial state.
        raise  # Propagate lock failure.


def release_file_lock(file_lock: FileLock) -> None:
    """
    Release one acquired file lock.

    :param file_lock: Acquired file lock.
    :return: None.
    """

    try:  # Release operating-system lock.
        if os.name == "nt":  # Use Windows byte-range unlocking on Windows.
            import msvcrt  # Import Windows lock support only on Windows.
            file_lock.stream.seek(0)  # Move to selected byte.
            msvcrt.locking(file_lock.stream.fileno(), msvcrt.LK_UNLCK, LOCK_BYTE_COUNT)  # Release one-byte lock.
        else:  # Use POSIX flock elsewhere.
            import fcntl  # Import POSIX lock support only on POSIX.
            fcntl.flock(file_lock.stream.fileno(), fcntl.LOCK_UN)  # Release POSIX lock.
    except OSError:  # Ignore release attempts for invalid lock state.
        pass  # Preserve cleanup stability.
    finally:  # Close owning stream.
        file_lock.stream.close()  # Close lock file stream.


def build_media_lock_path(file_path: Path) -> Path:
    """
    Build a cross-process lock path for one media file.

    :param file_path: Media file path.
    :return: Lock file path.
    """

    resolved_path = file_path.resolve(strict=False)  # Resolve media path without requiring existence.
    lock_identity = str(resolved_path).casefold() if os.name == "nt" else str(resolved_path)  # Normalize Windows path casing.
    lock_hash = hashlib.sha256(lock_identity.encode("utf-8")).hexdigest()  # Build deterministic lock identity.
    return MEDIA_LOCK_DIRECTORY / f"{lock_hash}.lock"  # Return lock file path.


def acquire_media_edit_lock(file_path: Path) -> FileLock:
    """
    Acquire an exclusive edit lock for one media file.

    :param file_path: Media file path.
    :return: Acquired file lock handle.
    """

    lock_path = build_media_lock_path(file_path)  # Build target lock path.
    owner_text = f"pid={os.getpid()}\nfile={file_path.resolve(strict=False)}\n"  # Build diagnostic lock payload.
    return acquire_file_lock(lock_path, owner_text)  # Return media edit lock.


def run_json_command(command: list[str], failure_label: str) -> dict[str, Any]:
    """
    Run one JSON-producing command and return parsed output.

    :param command: Command argument vector.
    :param failure_label: Context label for errors.
    :return: Parsed JSON object.
    """

    try:  # Run external tool without shell expansion.
        result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="replace")  # Execute command.
    except OSError as error:  # Handle executable launch failure.
        raise RuntimeError(f"{failure_label} could not start: {error}") from error  # Raise contextual launch error.

    if result.returncode != 0:  # Validate tool success.
        details = (result.stderr or result.stdout).strip() or "No diagnostic output was provided."  # Read tool diagnostics.
        raise RuntimeError(f"{failure_label} failed: {details}")  # Raise contextual tool failure.

    try:  # Parse tool JSON output.
        parsed_data = json.loads(result.stdout) if result.stdout else {}  # Decode JSON payload.
    except json.JSONDecodeError as error:  # Handle invalid JSON output.
        raise RuntimeError(f"{failure_label} returned invalid JSON.") from error  # Raise contextual JSON error.

    if not isinstance(parsed_data, dict):  # Validate expected JSON object shape.
        raise RuntimeError(f"{failure_label} returned unexpected JSON shape.")  # Raise contextual shape error.

    return parsed_data  # Return parsed object.


def probe_ffprobe(file_path: Path) -> dict[str, Any]:
    """
    Probe media through ffprobe.

    :param file_path: Media file path.
    :return: Parsed ffprobe metadata.
    """

    executable = find_executable("ffprobe")  # Locate ffprobe.
    if executable is None:  # Validate ffprobe availability.
        raise RuntimeError("ffprobe not found.")  # Raise missing-tool error.
    command = [executable, "-v", "error", "-show_streams", "-show_format", "-of", "json", str(file_path)]  # Build read-only ffprobe command.
    return run_json_command(command, f"ffprobe for {file_path}")  # Return parsed metadata.


def probe_mkvmerge(file_path: Path) -> dict[str, Any]:
    """
    Probe Matroska metadata through mkvmerge.

    :param file_path: Media file path.
    :return: Parsed mkvmerge metadata.
    """

    executable = find_executable("mkvmerge")  # Locate mkvmerge.
    if executable is None:  # Validate mkvmerge availability.
        raise RuntimeError("mkvmerge not found.")  # Raise missing-tool error.
    command = [executable, "-J", str(file_path)]  # Build read-only mkvmerge command.
    return run_json_command(command, f"mkvmerge for {file_path}")  # Return parsed metadata.


def read_streams_by_type(ffprobe_data: dict[str, Any], codec_type: str) -> list[dict[str, Any]]:
    """
    Return ffprobe streams matching one codec type.

    :param ffprobe_data: Parsed ffprobe data.
    :param codec_type: Requested codec type.
    :return: Ordered stream list.
    """

    raw_streams = ffprobe_data.get("streams")  # Read stream collection.
    streams = raw_streams if isinstance(raw_streams, list) else []  # Normalize malformed stream collection.
    return [stream for stream in streams if isinstance(stream, dict) and stream.get("codec_type") == codec_type]  # Return type-filtered streams.


def read_mkv_tracks_by_type(mkvmerge_data: dict[str, Any], track_type: str) -> list[dict[str, Any]]:
    """
    Return mkvmerge tracks matching one track type.

    :param mkvmerge_data: Parsed mkvmerge data.
    :param track_type: Requested mkvmerge track type.
    :return: Ordered track list.
    """

    raw_tracks = mkvmerge_data.get("tracks")  # Read track collection.
    tracks = raw_tracks if isinstance(raw_tracks, list) else []  # Normalize malformed track collection.
    return [track for track in tracks if isinstance(track, dict) and track.get("type") == track_type]  # Return type-filtered tracks.


def read_tags(stream: dict[str, Any]) -> dict[str, str]:
    """
    Read string tags from one ffprobe stream.

    :param stream: ffprobe stream object.
    :return: Stream tag mapping.
    """

    raw_tags = stream.get("tags")  # Read raw tags value.
    tags = raw_tags if isinstance(raw_tags, dict) else {}  # Normalize malformed tags.
    return {str(key): str(value) for key, value in tags.items() if value is not None}  # Return string tags.


def read_stream_default(stream: dict[str, Any]) -> bool:
    """
    Read default disposition from one ffprobe stream.

    :param stream: ffprobe stream object.
    :return: True when default disposition is enabled.
    """

    disposition = stream.get("disposition")  # Read disposition object.
    return isinstance(disposition, dict) and disposition.get("default") == 1  # Return normalized default flag.


def read_mkv_properties(track: dict[str, Any]) -> dict[str, Any]:
    """
    Read mkvmerge properties from one track.

    :param track: mkvmerge track object.
    :return: Track properties object.
    """

    raw_properties = track.get("properties")  # Read raw properties object.
    return raw_properties if isinstance(raw_properties, dict) else {}  # Return normalized properties.


def read_current_name(ffprobe_stream: dict[str, Any], mkv_track: dict[str, Any]) -> str:
    """
    Read current track name from mkvmerge or ffprobe metadata.

    :param ffprobe_stream: ffprobe stream object.
    :param mkv_track: mkvmerge track object.
    :return: Current track name.
    """

    properties = read_mkv_properties(mkv_track)  # Read Matroska track properties.
    for value in (properties.get("track_name"), properties.get("track_name_escaped"), read_tags(ffprobe_stream).get("title")):  # Iterate known name fields.
        if isinstance(value, str) and value.strip() != "":  # Validate visible name.
            return value.strip()  # Return normalized name.
    return ""  # Return empty name when absent.


def read_current_language_code(ffprobe_stream: dict[str, Any], mkv_track: dict[str, Any]) -> str:
    """
    Read current track language code from mkvmerge or ffprobe metadata.

    :param ffprobe_stream: ffprobe stream object.
    :param mkv_track: mkvmerge track object.
    :return: Current language code.
    """

    properties = read_mkv_properties(mkv_track)  # Read Matroska track properties.
    for value in (properties.get("language"), read_tags(ffprobe_stream).get("language")):  # Iterate legacy language fields.
        if isinstance(value, str) and value.strip() != "":  # Validate language text.
            return value.strip()  # Return normalized language code.
    return ""  # Return empty language code when absent.


def read_current_language_ietf(ffprobe_stream: dict[str, Any], mkv_track: dict[str, Any]) -> str:
    """
    Read current BCP-47 language code from mkvmerge or ffprobe metadata.

    :param ffprobe_stream: ffprobe stream object.
    :param mkv_track: mkvmerge track object.
    :return: Current BCP-47 language code.
    """

    properties = read_mkv_properties(mkv_track)  # Read Matroska track properties.
    for value in (properties.get("language_ietf"), read_tags(ffprobe_stream).get("LANGUAGE")):  # Iterate precise language fields.
        if isinstance(value, str) and value.strip() != "":  # Validate BCP-47 language text.
            return value.strip()  # Return normalized BCP-47 code.
    return ""  # Return empty BCP-47 code when absent.


def read_stream_index(ffprobe_stream: dict[str, Any], mkv_track: dict[str, Any]) -> int | None:
    """
    Read stable stream index from ffprobe or mkvmerge.

    :param ffprobe_stream: ffprobe stream object.
    :param mkv_track: mkvmerge track object.
    :return: Stream index or None.
    """

    for value in (ffprobe_stream.get("index"), mkv_track.get("id")):  # Iterate possible stream indexes.
        if isinstance(value, int):  # Validate integer index.
            return value  # Return stream index.
    return None  # Return no index.


def read_track_uid(mkv_track: dict[str, Any]) -> int | None:
    """
    Read Matroska Track UID from mkvmerge metadata.

    :param mkv_track: mkvmerge track object.
    :return: Track UID or None.
    """

    value = read_mkv_properties(mkv_track).get("uid")  # Read UID property.
    return value if isinstance(value, int) else None  # Return UID when numeric.


def build_stream_snapshots(ffprobe_streams: list[dict[str, Any]], mkv_tracks: list[dict[str, Any]], codec_type: str) -> list[StreamSnapshot]:
    """
    Build validated current stream snapshots from ffprobe and mkvmerge order.

    :param ffprobe_streams: Ordered ffprobe streams.
    :param mkv_tracks: Ordered mkvmerge tracks.
    :param codec_type: ffprobe codec type.
    :return: Ordered stream snapshots.
    """

    snapshots: list[StreamSnapshot] = []  # Store snapshots.
    for position, ffprobe_stream in enumerate(ffprobe_streams):  # Iterate report-order streams.
        mkv_track = mkv_tracks[position]  # Read matching mkvmerge track by type order.
        codec_name = str(ffprobe_stream.get("codec_name") or mkv_track.get("codec") or "")  # Read codec name.
        stream_index = read_stream_index(ffprobe_stream, mkv_track)  # Read stream index.
        track_uid = read_track_uid(mkv_track)  # Read Matroska Track UID.
        language_code = read_current_language_code(ffprobe_stream, mkv_track)  # Read current language code.
        language_ietf = read_current_language_ietf(ffprobe_stream, mkv_track)  # Read current BCP-47 language code.
        name = read_current_name(ffprobe_stream, mkv_track)  # Read current track name.
        default = read_stream_default(ffprobe_stream) or bool(read_mkv_properties(mkv_track).get("default_track") is True)  # Read current default flag.
        forced = bool(read_mkv_properties(mkv_track).get("forced_track") is True)  # Read current forced flag.
        snapshots.append(StreamSnapshot(position, stream_index, track_uid, codec_name, codec_type, language_code, language_ietf, name, default, forced))  # Store stream snapshot.
    return snapshots  # Return snapshots.


def resolve_snapshot_language(stream: StreamSnapshot, subtitle: bool) -> str:
    """
    Resolve current snapshot language with BCP-47 priority.

    :param stream: Current stream snapshot.
    :param subtitle: Whether subtitle-specific normalization is required.
    :return: Canonical language or empty text.
    """

    primary_value = stream.language_ietf if stream.language_ietf != "" else stream.language_code  # Prefer precise BCP-47 language when present.
    return normalize_subtitle_language_value(primary_value) if subtitle else normalize_language_value(primary_value)  # Return canonical current language.


def value_has_pt_br_indicator(value: object) -> bool:
    """
    Detect explicit Brazilian Portuguese evidence in one value.

    :param value: Raw report value.
    :return: True when Brazilian Portuguese evidence exists.
    """

    normalized_value = normalize_text(value)  # Normalize report value.
    compact_value = normalized_value.replace(" ", "")  # Build compact value for region tags.
    tokens = set(normalized_value.split())  # Build token set.
    if compact_value in {"ptbr", "pob", "pb", "bra"} or "ptbr" in compact_value:  # Detect compact Brazilian markers.
        return True  # Return positive marker.
    if "pt br" in normalized_value or "pob" in tokens or "pb" in tokens or "bra" in tokens:  # Detect separated Brazilian markers.
        return True  # Return positive marker.
    return bool(tokens.intersection(PT_BR_INDICATORS))  # Return token indicator result.


def resolve_report_language(prefix: str, parenthesized_values: list[str], fallback: str, subtitle: bool) -> str:
    """
    Resolve report language with prefix priority over existing title fallback.

    :param prefix: Report language prefix before title separator.
    :param parenthesized_values: Parenthesized metadata hints from prefix.
    :param fallback: Existing title fallback after separator.
    :param subtitle: Whether subtitle-specific normalization is required.
    :return: Canonical language or empty text.
    """

    prefix_context = " ".join([prefix, *parenthesized_values]).strip()  # Combine report-authored language context.
    if value_has_pt_br_indicator(prefix_context):  # Detect explicit Brazilian Portuguese context.
        return "Brazilian Portuguese"  # Return precise PT-BR language.

    normalized_prefix = normalize_subtitle_language_value(prefix) if subtitle else normalize_language_value(prefix)  # Resolve prefix language.
    if normalized_prefix != "":  # Use report prefix when known.
        return normalized_prefix  # Return prefix-derived language.

    for value in parenthesized_values:  # Iterate supporting parenthesized values.
        normalized_value = normalize_subtitle_language_value(value) if subtitle else normalize_language_value(value)  # Resolve supporting value.
        if normalized_value != "":  # Use supporting value when known.
            return normalized_value  # Return supporting language.

    return normalize_subtitle_language_value(fallback) if subtitle else normalize_language_value(fallback)  # Return title fallback only after prefix fails.


def extract_parenthesized_values(value: str) -> list[str]:
    """
    Extract parenthesized metadata values from report text.

    :param value: Report track text.
    :return: Parenthesized values.
    """

    return [match.group("value").strip() for match in PAREN_LANGUAGE_PATTERN.finditer(value)]  # Return matched values.


def normalize_subtitle_type_value(value: object) -> str:
    """
    Resolve one subtitle type value into canonical form.

    :param value: Raw subtitle type text.
    :return: Canonical subtitle type or empty text.
    """

    normalized_value = normalize_text(value)  # Normalize text for accent-insensitive matching.
    tokens = set(normalized_value.split())  # Build full-token lookup.
    if tokens.intersection({"forced", "forcada", "forcado"}):  # Detect explicit forced-subtitle wording.
        return "Forced"  # Return canonical forced type.
    if tokens.intersection({"full", "complete", "completa", "completo"}):  # Detect explicit full-subtitle wording.
        return "Full"  # Return canonical full type.
    return ""  # Return unknown type.


def build_subtitle_detected_name(detected_language: str, detected_type: str) -> str:
    """
    Build canonical subtitle name from detected type and language.

    :param detected_language: Canonical subtitle language.
    :param detected_type: Canonical subtitle type.
    :return: Canonical subtitle name or empty text.
    """

    if detected_language == "":  # Detect missing language.
        return ""  # Return unknown target.
    if detected_type == "":  # Detect missing subtitle type.
        return detected_language  # Return language-only fallback.
    return f"{detected_type} {detected_language}"  # Return type-before-language target.


def resolve_subtitle_target_name(report_track: ReportSubtitleTrack, current_track: StreamSnapshot) -> str:
    """
    Resolve canonical subtitle target name from report and forced metadata.

    :param report_track: Parsed report subtitle track.
    :param current_track: Current subtitle stream snapshot.
    :return: Canonical subtitle target name.
    """

    if report_track.target_name == "" or report_track.language == "":  # Detect unresolved subtitle metadata.
        return ""  # Return unknown target.
    if report_track.target_name != report_track.language:  # Preserve report-established Full or Forced classification.
        return report_track.target_name  # Return report canonical target.
    if current_track.forced:  # Prefer actual forced flag when report lacks classification.
        return build_subtitle_detected_name(report_track.language, "Forced")  # Return forced canonical target.
    return report_track.target_name  # Return language-only target.


def parse_audio_report_track(raw_text: object, position: int) -> ReportAudioTrack:
    """
    Parse one report audio row into intended metadata.

    :param raw_text: Raw report audio row.
    :param position: Zero-based audio position.
    :return: Parsed report audio track.
    """

    text = str(raw_text or "").strip()  # Normalize report row.
    report_default = DEFAULT_SUFFIX_PATTERN.search(text) is not None  # Read report default marker.
    clean_text = DEFAULT_SUFFIX_PATTERN.sub("", text).strip()  # Remove report default marker.
    before_dash, separator, after_dash = clean_text.partition(" - ")  # Split language prefix from optional title.
    parenthesized_values = extract_parenthesized_values(before_dash)  # Read parenthesized language hints.
    prefix_without_parens = PAREN_LANGUAGE_PATTERN.sub(" ", before_dash).strip()  # Remove parenthesized text from prefix.
    language = resolve_report_language(prefix_without_parens, parenthesized_values, after_dash if separator else "", False)  # Resolve intended language from report prefix first.
    language_code = LANGUAGE_CODES.get(language, "")  # Resolve Matroska language code.
    language_ietf = LANGUAGE_IETF_CODES.get(language, "")  # Resolve precise BCP-47 language code.
    target_name = language if language != "" else ""  # Build reference-style audio name.
    secondary = bool(COMMENTARY_MARKERS.intersection(set(normalize_text(clean_text).split())))  # Detect secondary-audio markers.
    return ReportAudioTrack(position, text, language, language_code, language_ietf, target_name, report_default, secondary)  # Return parsed audio row.


def parse_subtitle_report_track(raw_text: object, position: int) -> ReportSubtitleTrack:
    """
    Parse one report subtitle row into intended metadata.

    :param raw_text: Raw report subtitle row.
    :param position: Zero-based subtitle position.
    :return: Parsed report subtitle track.
    """

    text = str(raw_text or "").strip()  # Normalize report row.
    internal_match = INTERNAL_SUBTITLE_PATTERN.match(text)  # Match internal subtitle marker.
    if internal_match is None:  # Detect external subtitle row.
        return ReportSubtitleTrack(position, text, "", "", "", "", False)  # Return non-internal row.

    body = internal_match.group("body").strip()  # Read internal subtitle body.
    before_dash, separator, after_dash = body.partition(" - ")  # Split language and title regions.
    parenthesized_values = extract_parenthesized_values(before_dash)  # Read parenthesized codec values for exclusion.
    prefix_without_parens = PAREN_LANGUAGE_PATTERN.sub(" ", before_dash).strip()  # Remove codec parenthetical from language prefix.
    language = resolve_report_language(prefix_without_parens, parenthesized_values, after_dash if separator else "", True)  # Resolve intended subtitle language from report prefix first.
    if language == "Portuguese" and value_has_pt_br_indicator(after_dash):  # Upgrade generic subtitle prefix when report title proves PT-BR.
        language = "Brazilian Portuguese"  # Preserve explicit subtitle PT-BR semantics.
    language_code = LANGUAGE_CODES.get(language, "")  # Resolve Matroska language code.
    language_ietf = LANGUAGE_IETF_CODES.get(language, "")  # Resolve precise BCP-47 language code.
    detected_type = normalize_subtitle_type_value(after_dash) if separator else ""  # Resolve subtitle type from report title.
    target_name = build_subtitle_detected_name(language, detected_type)  # Build reference-style subtitle target name.
    return ReportSubtitleTrack(position, text, language, language_code, language_ietf, target_name, True)  # Return parsed subtitle row.


def load_report(report_path: Path) -> dict[str, Any]:
    """
    Load one JSON report object.

    :param report_path: Report JSON path.
    :return: Parsed report object.
    """

    try:  # Read and parse JSON report.
        report_data = json.loads(report_path.read_text(encoding="utf-8"))  # Load JSON text.
    except (OSError, json.JSONDecodeError) as error:  # Handle unreadable or malformed report.
        raise RuntimeError(f"Report could not be read: {report_path}: {error}") from error  # Raise contextual report error.

    if not isinstance(report_data, dict):  # Validate top-level object shape.
        raise RuntimeError(f"Report top-level JSON value must be an object: {report_path}")  # Raise report shape error.

    return report_data  # Return parsed report.


def collect_movie_lists(report_data: dict[str, Any]) -> list[list[dict[str, Any]]]:
    """
    Collect movie-entry lists from one report object.

    :param report_data: Parsed report object.
    :return: Movie-entry lists.
    """

    movie_lists: list[list[dict[str, Any]]] = []  # Store report movie lists.
    for key, value in report_data.items():  # Iterate top-level report sections.
        if key == "InputDir":  # Skip input-directory marker.
            continue  # Continue to next section.
        if not isinstance(value, list):  # Skip non-list sections.
            continue  # Continue to next section.
        if key == "UnknownDefaultAudioLanguage" or REPORT_MOVIES_KEY_PATTERN.match(str(key)) is not None:  # Accept known report movie sections.
            movie_lists.append([entry for entry in value if isinstance(entry, dict)])  # Store object-shaped entries only.
    return movie_lists  # Return collected lists.


def collect_report_entries(report_paths: list[Path], summary: WorkflowSummary) -> list[MovieReportEntry]:
    """
    Collect movie entries from report paths.

    :param report_paths: Report JSON paths.
    :param summary: Mutable workflow summary.
    :return: Parsed movie entries.
    """

    entries: list[MovieReportEntry] = []  # Store parsed entries.
    for report_path in report_paths:  # Iterate requested reports.
        report_data = load_report(report_path)  # Load report JSON.
        input_dir_value = report_data.get("InputDir")  # Read report input root.
        input_dir = Path(input_dir_value) if isinstance(input_dir_value, str) and input_dir_value.strip() != "" else report_path.parent  # Resolve progress-relative root.
        summary.reports += 1  # Count loaded report.
        for movie_list in collect_movie_lists(report_data):  # Iterate movie sections.
            for raw_entry in movie_list:  # Iterate raw movie entries.
                full_path_value = raw_entry.get("FullPath")  # Read reported media path.
                if not isinstance(full_path_value, str) or full_path_value.strip() == "":  # Validate media path value.
                    summary.skipped += 1  # Count malformed movie entry.
                    summary.messages.append(f"Skipped report entry without FullPath in {report_path}")  # Store skip reason.
                    continue  # Skip malformed entry.
                audio_values = raw_entry.get("AudioTracks") if isinstance(raw_entry.get("AudioTracks"), list) else []  # Read audio rows.
                subtitle_values = raw_entry.get("SubtitleTracks") if isinstance(raw_entry.get("SubtitleTracks"), list) else []  # Read subtitle rows.
                audio_tracks = [parse_audio_report_track(value, index) for index, value in enumerate(audio_values)]  # Parse audio rows by report order.
                subtitle_tracks = [parse_subtitle_report_track(value, index) for index, value in enumerate(subtitle_values)]  # Parse subtitle rows by report order.
                entries.append(MovieReportEntry(report_path, input_dir, Path(full_path_value), audio_tracks, subtitle_tracks))  # Store parsed movie entry.
    return entries  # Return parsed entries.


def build_progress_media_path(movie: MovieReportEntry) -> str:
    """
    Build a compact progress label for one media file.

    :param movie: Parsed movie report entry.
    :return: Relative media path text.
    """

    try:  # Resolve path relative to the report input root.
        relative_path = movie.full_path.relative_to(movie.input_dir)  # Build report-root relative path.
        return str(relative_path)  # Return compact report-relative path.
    except ValueError:  # Handle files outside the report input root.
        pass  # Continue to current-directory fallback.

    try:  # Resolve path relative to the current working directory.
        relative_path = movie.full_path.relative_to(Path.cwd())  # Build cwd-relative path.
        return str(relative_path)  # Return compact cwd-relative path.
    except ValueError:  # Handle files outside the current working directory.
        pass  # Continue to absolute fallback.

    return str(movie.full_path)  # Return absolute path when no relative base applies.


def build_track_selector(track_type: str, position: int, track_uid: int | None) -> str:
    """
    Build a mkvpropedit selector for one target track.

    :param track_type: MKVToolNix selector type letter.
    :param position: Zero-based type-specific position.
    :param track_uid: Matroska Track UID when available.
    :return: mkvpropedit track selector.
    """

    if track_uid is not None:  # Prefer stable Matroska Track UID selector.
        return f"track:={track_uid}"  # Return UID selector.
    return f"track:{track_type}{position + 1}"  # Return type ordinal selector.


def merge_track_edits(edits: list[TrackEdit]) -> list[TrackEdit]:
    """
    Merge compatible edit groups for the same track selector.

    :param edits: Track edit requests.
    :return: Merged track edit requests.
    """

    merged_edits: dict[str, TrackEdit] = {}  # Store merged edits by selector.
    for edit in edits:  # Iterate requested edits.
        existing_edit = merged_edits.get(edit.selector)  # Read existing edit for selector.
        if existing_edit is None:  # Detect first edit for selector.
            merged_edits[edit.selector] = edit  # Store first edit.
            continue  # Continue to next edit.
        new_name = edit.new_name if edit.new_name is not None else existing_edit.new_name  # Prefer latest explicit name.
        language_code = edit.language_code if edit.language_code is not None else existing_edit.language_code  # Prefer latest explicit language.
        language_ietf = edit.language_ietf if edit.language_ietf is not None else existing_edit.language_ietf  # Prefer latest explicit BCP-47 language.
        default_flag = edit.default_flag if edit.default_flag is not None else existing_edit.default_flag  # Prefer latest explicit default flag.
        merged_edits[edit.selector] = TrackEdit(edit.selector, existing_edit.current_name, new_name, language_code, language_ietf, default_flag)  # Store merged edit.
    return list(merged_edits.values())  # Return merged edits in original selector order.


def valid_track_selector(selector: str) -> bool:
    """
    Validate one generated track selector.

    :param selector: mkvpropedit selector.
    :return: True when selector is permitted.
    """

    if selector.startswith("track:="):  # Accept UID selector prefix.
        return selector[7:].isdigit()  # Return numeric UID validation.
    if selector.startswith("track:a") or selector.startswith("track:s"):  # Accept audio and subtitle ordinal selectors.
        return selector[7:].isdigit()  # Return numeric ordinal validation.
    return False  # Reject unsupported selectors.


def append_track_edit_arguments(command: list[str], edit: TrackEdit) -> int:
    """
    Append one track edit group to an mkvpropedit command.

    :param command: Mutable command vector.
    :param edit: Track edit request.
    :return: Number of appended setters.
    """

    if not valid_track_selector(edit.selector):  # Validate selector scope.
        return 0  # Return no setters for invalid selector.
    edit_group = ["--edit", edit.selector]  # Start edit group.
    setter_count = 0  # Count setters in edit group.
    if edit.new_name is not None and edit.new_name.strip() != "" and edit.new_name != edit.current_name:  # Validate needed name setter.
        edit_group.extend(["--set", f"name={edit.new_name.strip()}"])  # Add name setter.
        setter_count += 1  # Count name setter.
    if edit.language_code is not None and edit.language_code.strip() != "":  # Validate language setter.
        edit_group.extend(["--set", f"language={edit.language_code.strip()}"])  # Add language setter.
        setter_count += 1  # Count language setter.
    if edit.language_ietf is not None and edit.language_ietf.strip() != "":  # Validate BCP-47 language setter.
        edit_group.extend(["--set", f"language-ietf={edit.language_ietf.strip()}"])  # Add BCP-47 language setter.
        setter_count += 1  # Count BCP-47 language setter.
    if edit.default_flag is not None:  # Validate default setter request.
        flag_value = "1" if edit.default_flag else "0"  # Convert default flag to mkvpropedit value.
        edit_group.extend(["--set", f"flag-default={flag_value}"])  # Add default-flag setter.
        setter_count += 1  # Count default setter.
    if setter_count > 0:  # Validate edit group has work.
        command.extend(edit_group)  # Append complete edit group.
    return setter_count  # Return setter count.


def build_mkvpropedit_command(file_path: Path, edits: list[TrackEdit], executable: str) -> tuple[list[str], int]:
    """
    Build a permitted mkvpropedit command.

    :param file_path: Target media file.
    :param edits: Track edit requests.
    :param executable: mkvpropedit executable path.
    :return: Command vector and setter count.
    """

    command = [executable, str(file_path)]  # Start command with executable and media path.
    setter_count = 0  # Store total setter count.
    for edit in merge_track_edits(edits):  # Iterate validated merged edits.
        setter_count += append_track_edit_arguments(command, edit)  # Append edit group and count setters.
    return command, setter_count  # Return command and requested setter count.


def setter_argument_permitted(selector: str, setter_value: str) -> bool:
    """
    Determine whether one setter argument is permitted.

    :param selector: mkvpropedit track selector.
    :param setter_value: mkvpropedit setter value.
    :return: True when setter scope is permitted.
    """

    if setter_value.startswith("name="):  # Accept track-name setter.
        return True  # Return accepted name setter.
    if setter_value.startswith("language="):  # Accept legacy language setter.
        return True  # Return accepted language setter.
    if setter_value.startswith("language-ietf="):  # Accept BCP-47 language setter.
        return True  # Return accepted BCP-47 setter.
    if setter_value in {"flag-default=0", "flag-default=1"} and (selector.startswith("track:a") or selector.startswith("track:=")):  # Accept audio default-flag setter.
        return True  # Return accepted default setter.
    return False  # Reject every other setter.


def command_scope_permitted(command: list[str]) -> bool:
    """
    Determine whether a generated mkvpropedit command stays within metadata scope.

    :param command: Generated command vector.
    :return: True when command is limited to permitted metadata setters.
    """

    if len(command) < 2:  # Validate executable and file path exist.
        return False  # Return invalid command.

    index = 2  # Start after executable and file path.
    while index < len(command):  # Iterate edit groups.
        if index + 3 >= len(command):  # Validate edit group length.
            return False  # Return invalid command.
        if command[index] != "--edit":  # Validate edit group marker.
            return False  # Return invalid command.
        selector = command[index + 1]  # Read track selector.
        if not valid_track_selector(selector):  # Validate track selector.
            return False  # Return invalid command.
        index += 2  # Advance to setters.
        setter_count = 0  # Count setters.
        while index < len(command) and command[index] == "--set":  # Iterate setters.
            if index + 1 >= len(command):  # Validate setter value exists.
                return False  # Return invalid command.
            if not setter_argument_permitted(selector, command[index + 1]):  # Validate setter scope.
                return False  # Return invalid command.
            setter_count += 1  # Count accepted setter.
            index += 2  # Advance to next argument.
        if setter_count == 0:  # Validate edit group has setters.
            return False  # Return invalid command.

    return True  # Return permitted command.


def run_mkvpropedit(file_path: Path, edits: list[TrackEdit], apply_changes: bool) -> EditExecutionResult:
    """
    Run or preview mkvpropedit edits.

    :param file_path: Target media file.
    :param edits: Track edit requests.
    :param apply_changes: Whether changes should be applied.
    :return: Edit execution result.
    """

    executable = find_executable("mkvpropedit")  # Locate mkvpropedit executable.
    if executable is None:  # Validate mkvpropedit availability.
        return EditExecutionResult(False, False, 0, "mkvpropedit not found")  # Return missing-tool result.

    command, setter_count = build_mkvpropedit_command(file_path, edits, executable)  # Build mkvpropedit command.
    if setter_count == 0:  # Detect no-op command.
        return EditExecutionResult(True, False, 0, "No metadata edits needed")  # Return no-op success.
    if not command_scope_permitted(command):  # Validate command scope before mutation.
        return EditExecutionResult(False, False, setter_count, "unsafe mkvpropedit command rejected")  # Return rejected command.
    if not apply_changes:  # Honor dry-run mode.
        return EditExecutionResult(True, False, setter_count, "Dry-run only")  # Return preview success.

    try:  # Run mutation while caller owns lock.
        result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="replace")  # Execute mkvpropedit.
    except OSError as error:  # Handle execution failure.
        return EditExecutionResult(False, False, setter_count, str(error))  # Return launch failure.

    success = result.returncode in {0, 1}  # Treat MKVToolNix warning exit as completed.
    warning = result.returncode == 1  # Preserve MKVToolNix warning status.
    details = (result.stderr or result.stdout).strip()  # Capture diagnostics.
    return EditExecutionResult(success, warning, setter_count, details)  # Return command result.


def select_default_audio_track(audio_tracks: list[ReportAudioTrack]) -> tuple[int | None, str]:
    """
    Select deterministic original-language default audio from report semantics.

    :param audio_tracks: Parsed report audio rows.
    :return: Selected zero-based audio position and reason.
    """

    known_tracks = [track for track in audio_tracks if track.language != ""]  # Keep rows with resolved language.
    if len(known_tracks) == 1:  # Accept single known audio stream.
        return known_tracks[0].position, "single known audio stream"  # Return only known track.

    original_candidates = [track for track in known_tracks if track.language != "Brazilian Portuguese" and not track.secondary]  # Collect primary non-Brazilian Portuguese candidates.
    candidate_languages = sorted({track.language for track in original_candidates})  # Collect unique non-Portuguese candidate languages.
    if len(original_candidates) == 1:  # Accept exactly one non-Portuguese candidate.
        return original_candidates[0].position, f"{original_candidates[0].language} original-language candidate"  # Return unique candidate.
    if len(original_candidates) == 0:  # Detect absence of an original-language candidate.
        return None, "no non-Brazilian Portuguese original-language candidate"  # Return missing reason.
    return None, f"ambiguous original-language candidates: {', '.join(candidate_languages)}"  # Return ambiguity reason.


def validate_file_support(file_path: Path) -> str:
    """
    Validate whether one media file can be mutated safely.

    :param file_path: Media file path.
    :return: Empty text when supported, otherwise reason.
    """

    if not file_path.exists():  # Validate target existence.
        return "file not found"  # Return missing-file reason.
    if not file_path.is_file():  # Validate target is a file.
        return "path is not a file"  # Return non-file reason.
    try:  # Read file size before tool usage.
        if file_path.stat().st_size == 0:  # Validate non-empty file.
            return "empty media file (0 bytes)"  # Return empty-file reason.
    except OSError as error:  # Handle unreadable filesystem metadata.
        return f"unreadable media file: {error}"  # Return stat failure reason.
    suffix = file_path.suffix.lower()  # Normalize file extension.
    if suffix not in SUPPORTED_MKV_EXTENSIONS:  # Refuse unsupported containers.
        if suffix in UNSUPPORTED_MUTATION_EXTENSIONS:  # Identify known unsupported report containers.
            return f"unsupported container for in-place metadata mutation: {suffix}"  # Return precise unsupported reason.
        return f"unsupported container: {suffix or '<none>'}"  # Return generic unsupported reason.
    return ""  # Return supported marker.


def build_current_snapshots(file_path: Path) -> tuple[list[StreamSnapshot], list[StreamSnapshot]]:
    """
    Build current audio and subtitle snapshots for one Matroska file.

    :param file_path: Media file path.
    :return: Audio and subtitle snapshots.
    """

    ffprobe_data = probe_ffprobe(file_path)  # Probe current stream metadata through ffprobe.
    mkvmerge_data = probe_mkvmerge(file_path)  # Probe current Matroska track metadata through mkvmerge.
    ffprobe_audio = read_streams_by_type(ffprobe_data, "audio")  # Read ffprobe audio streams in report order.
    ffprobe_subtitles = read_streams_by_type(ffprobe_data, "subtitle")  # Read ffprobe subtitle streams in report order.
    mkv_audio = read_mkv_tracks_by_type(mkvmerge_data, "audio")  # Read mkvmerge audio tracks in edit order.
    mkv_subtitles = read_mkv_tracks_by_type(mkvmerge_data, "subtitles")  # Read mkvmerge subtitle tracks in edit order.
    if len(ffprobe_audio) != len(mkv_audio):  # Validate audio order can be mapped.
        raise RuntimeError(f"audio stream count mismatch: ffprobe={len(ffprobe_audio)}, mkvmerge={len(mkv_audio)}")  # Raise mapping failure.
    if len(ffprobe_subtitles) != len(mkv_subtitles):  # Validate subtitle order can be mapped.
        raise RuntimeError(f"subtitle stream count mismatch: ffprobe={len(ffprobe_subtitles)}, mkvmerge={len(mkv_subtitles)}")  # Raise mapping failure.
    audio_snapshots = build_stream_snapshots(ffprobe_audio, mkv_audio, "audio")  # Build audio snapshots.
    subtitle_snapshots = build_stream_snapshots(ffprobe_subtitles, mkv_subtitles, "subtitle")  # Build subtitle snapshots.
    return audio_snapshots, subtitle_snapshots  # Return stream snapshots.


def plan_audio_metadata_edits(movie: MovieReportEntry, current_audio: list[StreamSnapshot], summary: WorkflowSummary) -> tuple[list[TrackEdit], int | None]:
    """
    Plan audio name, language, and default metadata edits.

    :param movie: Parsed movie report entry.
    :param current_audio: Current audio stream snapshots.
    :param summary: Mutable workflow summary.
    :return: Planned edits and selected default audio position.
    """

    edits: list[TrackEdit] = []  # Store planned audio edits.
    if len(movie.audio_tracks) != len(current_audio):  # Validate report-to-stream mapping by count.
        summary.failed += 1  # Count mapping failure.
        summary.messages.append(f"Audio mapping mismatch for {movie.full_path}: report={len(movie.audio_tracks)}, file={len(current_audio)}")  # Store mapping failure.
        return [], None  # Return no edits.

    default_position, default_reason = select_default_audio_track(movie.audio_tracks)  # Resolve intended audio default.
    if default_position is None:  # Detect unresolvable default target.
        summary.skipped += 1  # Count default skip.
        summary.messages.append(f"Default audio unchanged for {movie.full_path}: {default_reason}")  # Store default skip reason.
    else:  # Record deterministic default target selection.
        summary.messages.append(f"Default audio target for {movie.full_path}: audio {default_position + 1} from {default_reason}")  # Store selected default reason.

    if default_position is not None:  # Add default-flag operations for every audio stream.
        for current_track in current_audio:  # Iterate all targetable audio streams.
            selector = build_track_selector("a", current_track.position, current_track.track_uid)  # Build safe mkvpropedit selector.
            target_default = current_track.position == default_position  # Resolve desired default state.
            default_flag = target_default if current_track.default != target_default else None  # Set default only when different.
            if default_flag is None:  # Detect no default change for this stream.
                continue  # Continue to metadata edits.
            edits.append(TrackEdit(selector, current_track.name, None, None, None, default_flag))  # Store default edit for targetable stream.

    for report_track in movie.audio_tracks:  # Iterate report audio tracks by stream order.
        if report_track.language == "" or report_track.language_code == "" or report_track.target_name == "":  # Validate target metadata is known.
            summary.skipped += 1  # Count unresolved audio row.
            summary.messages.append(f"Audio metadata unchanged for {movie.full_path} audio {report_track.position + 1}: unresolved report language {report_track.raw_text!r}")  # Store unresolved reason.
            continue  # Skip unresolved row.
        current_track = current_audio[report_track.position]  # Read matching current stream by report order.
        selector = build_track_selector("a", current_track.position, current_track.track_uid)  # Build safe mkvpropedit selector.
        current_language = resolve_snapshot_language(current_track, False)  # Normalize current language for comparison.
        new_language_code = report_track.language_code if current_language != report_track.language else None  # Set legacy language only when different.
        new_language_ietf = report_track.language_ietf if current_track.language_ietf != report_track.language_ietf else None  # Set BCP-47 language only when different.
        new_name = report_track.target_name if current_track.name != report_track.target_name else None  # Set name only when different.
        if new_name is None and new_language_code is None and new_language_ietf is None:  # Detect no-op audio row.
            continue  # Skip no-op audio row.
        edits.append(TrackEdit(selector, current_track.name, new_name, new_language_code, new_language_ietf, None))  # Store audio metadata edit.

    return edits, default_position  # Return planned audio edits and default target.


def plan_subtitle_metadata_edits(movie: MovieReportEntry, current_subtitles: list[StreamSnapshot], summary: WorkflowSummary) -> list[TrackEdit]:
    """
    Plan internal subtitle name and language metadata edits.

    :param movie: Parsed movie report entry.
    :param current_subtitles: Current subtitle stream snapshots.
    :param summary: Mutable workflow summary.
    :return: Planned subtitle edits.
    """

    internal_tracks = [track for track in movie.subtitle_tracks if track.internal]  # Keep only internal subtitle rows.
    external_tracks = [track for track in movie.subtitle_tracks if not track.internal]  # Collect external subtitle rows.
    edits: list[TrackEdit] = []  # Store planned subtitle edits.
    summary.skipped += len(external_tracks)  # Count external subtitle rows as intentionally skipped.
    if len(internal_tracks) != len(current_subtitles):  # Validate internal subtitle report mapping by count.
        summary.failed += 1  # Count mapping failure.
        summary.messages.append(f"Subtitle mapping mismatch for {movie.full_path}: report_internal={len(internal_tracks)}, file={len(current_subtitles)}")  # Store mapping failure.
        return []  # Return no subtitle edits.

    for report_track, current_track in zip(internal_tracks, current_subtitles):  # Iterate report and current subtitles by verified order.
        if report_track.language == "" or report_track.language_code == "" or report_track.target_name == "":  # Validate target metadata is known.
            summary.skipped += 1  # Count unresolved subtitle row.
            summary.messages.append(f"Subtitle metadata unchanged for {movie.full_path} subtitle {report_track.position + 1}: unresolved report language {report_track.raw_text!r}")  # Store unresolved reason.
            continue  # Skip unresolved row.
        selector = build_track_selector("s", current_track.position, current_track.track_uid)  # Build safe mkvpropedit selector.
        target_name = resolve_subtitle_target_name(report_track, current_track)  # Resolve reference-style subtitle name.
        current_language = resolve_snapshot_language(current_track, True)  # Normalize current subtitle language.
        new_language_code = report_track.language_code if current_language != report_track.language else None  # Set legacy language only when different.
        new_language_ietf = report_track.language_ietf if current_track.language_ietf != report_track.language_ietf else None  # Set BCP-47 language only when different.
        new_name = target_name if current_track.name != target_name else None  # Set name only when different.
        if new_name is None and new_language_code is None and new_language_ietf is None:  # Detect no-op subtitle row.
            continue  # Skip no-op subtitle row.
        edits.append(TrackEdit(selector, current_track.name, new_name, new_language_code, new_language_ietf, None))  # Store subtitle edit.

    return edits  # Return planned subtitle edits.


def plan_file_edits(movie: MovieReportEntry, summary: WorkflowSummary) -> PlannedFileEdit | None:
    """
    Plan all safe metadata edits for one report movie entry.

    :param movie: Parsed movie report entry.
    :param summary: Mutable workflow summary.
    :return: Planned file edit or None.
    """

    support_issue = validate_file_support(movie.full_path)  # Validate media support.
    if support_issue != "":  # Detect unsupported or invalid media.
        summary.skipped += 1  # Count skipped file.
        summary.messages.append(f"Skipped {movie.full_path}: {support_issue}")  # Store skip reason.
        return None  # Return no plan.

    try:  # Probe current media metadata.
        current_audio, current_subtitles = build_current_snapshots(movie.full_path)  # Build current snapshots.
    except RuntimeError as error:  # Handle probing or mapping failures.
        summary.failed += 1  # Count probe failure.
        summary.messages.append(f"Metadata probe failed for {movie.full_path}: {error}")  # Store failure reason.
        return None  # Return no plan.

    internal_subtitles = [track for track in movie.subtitle_tracks if track.internal]  # Collect report internal subtitles.
    if len(movie.audio_tracks) != len(current_audio):  # Validate complete audio report mapping before any edit planning.
        summary.failed += 1  # Count mapping failure.
        summary.messages.append(f"File plan aborted for {movie.full_path}: audio mapping mismatch report={len(movie.audio_tracks)}, file={len(current_audio)}")  # Store mapping failure.
        return None  # Return no plan.
    if len(internal_subtitles) != len(current_subtitles):  # Validate complete subtitle report mapping before any edit planning.
        summary.failed += 1  # Count mapping failure.
        summary.messages.append(f"File plan aborted for {movie.full_path}: subtitle mapping mismatch report_internal={len(internal_subtitles)}, file={len(current_subtitles)}")  # Store mapping failure.
        return None  # Return no plan.

    audio_edits, default_position = plan_audio_metadata_edits(movie, current_audio, summary)  # Plan audio metadata edits.
    subtitle_edits = plan_subtitle_metadata_edits(movie, current_subtitles, summary)  # Plan subtitle metadata edits.
    edits = audio_edits + subtitle_edits  # Combine edit lists.
    if not edits:  # Detect no-op file.
        summary.skipped += 1  # Count no-op file.
        summary.messages.append(f"No metadata changes needed for {movie.full_path}")  # Store no-op message.
        return None  # Return no plan.

    summary.planned_files += 1  # Count file with planned changes.
    summary.planned_edits += sum(1 for edit in edits for value in (edit.new_name, edit.language_code, edit.language_ietf, edit.default_flag) if value is not None)  # Count planned setters.
    return PlannedFileEdit(movie, current_audio, current_subtitles, edits, default_position)  # Return validated plan.


def validate_order_unchanged(before: list[StreamSnapshot], after: list[StreamSnapshot], label: str) -> str:
    """
    Validate that stream count, order, and codecs stayed unchanged.

    :param before: Pre-edit stream snapshots.
    :param after: Post-edit stream snapshots.
    :param label: Stream label for diagnostics.
    :return: Empty text when unchanged, otherwise reason.
    """

    if len(before) != len(after):  # Validate stream count.
        return f"{label} stream count changed: before={len(before)}, after={len(after)}"  # Return count-change reason.
    for before_stream, after_stream in zip(before, after):  # Iterate paired streams by order.
        if before_stream.codec_type != after_stream.codec_type:  # Validate codec type stayed stable.
            return f"{label} codec type changed at position {before_stream.position + 1}"  # Return type-change reason.
        if before_stream.codec_name != after_stream.codec_name:  # Validate codec name stayed stable.
            return f"{label} codec changed at position {before_stream.position + 1}"  # Return codec-change reason.
        if before_stream.stream_index != after_stream.stream_index:  # Validate stream index stayed stable.
            return f"{label} stream index changed at position {before_stream.position + 1}"  # Return index-change reason.
    return ""  # Return unchanged marker.


def validate_expected_metadata(plan: PlannedFileEdit) -> str:
    """
    Validate expected metadata after mutation.

    :param plan: Applied file edit plan.
    :return: Empty text when metadata matches, otherwise reason.
    """

    after_audio, after_subtitles = build_current_snapshots(plan.movie.full_path)  # Reprobe current metadata after edit.
    audio_order_issue = validate_order_unchanged(plan.before_audio, after_audio, "audio")  # Validate audio order and codecs.
    if audio_order_issue != "":  # Detect audio integrity issue.
        return audio_order_issue  # Return audio issue.
    subtitle_order_issue = validate_order_unchanged(plan.before_subtitles, after_subtitles, "subtitle")  # Validate subtitle order and codecs.
    if subtitle_order_issue != "":  # Detect subtitle integrity issue.
        return subtitle_order_issue  # Return subtitle issue.

    if plan.default_audio_position is not None:  # Validate default audio flags when selected.
        default_positions = [stream.position for stream in after_audio if stream.default]  # Collect default audio positions.
        if default_positions != [plan.default_audio_position]:  # Validate exactly intended default.
            return f"default audio mismatch: expected={[plan.default_audio_position]}, actual={default_positions}"  # Return default mismatch.

    for report_track in plan.movie.audio_tracks:  # Iterate expected audio metadata.
        if report_track.language == "" or report_track.language_code == "" or report_track.position >= len(after_audio):  # Skip unresolved or absent audio rows.
            continue  # Continue to next audio row.
        stream = after_audio[report_track.position]  # Read post-edit audio stream.
        if resolve_snapshot_language(stream, False) != report_track.language:  # Validate audio language.
            return f"audio {report_track.position + 1} language mismatch: expected={report_track.language}, actual={stream.language_ietf or stream.language_code}"  # Return language mismatch.
        if report_track.language_ietf != "" and stream.language_ietf != report_track.language_ietf:  # Validate precise audio BCP-47 language.
            return f"audio {report_track.position + 1} BCP-47 language mismatch: expected={report_track.language_ietf}, actual={stream.language_ietf}"  # Return BCP-47 mismatch.
        if stream.name != report_track.target_name:  # Validate audio name.
            return f"audio {report_track.position + 1} name mismatch: expected={report_track.target_name!r}, actual={stream.name!r}"  # Return name mismatch.

    internal_tracks = [track for track in plan.movie.subtitle_tracks if track.internal]  # Collect expected internal subtitle rows.
    for report_track, stream in zip(internal_tracks, after_subtitles):  # Iterate expected subtitle metadata.
        if report_track.language == "" or report_track.language_code == "":  # Skip unresolved subtitle rows.
            continue  # Continue to next subtitle row.
        if resolve_snapshot_language(stream, True) != report_track.language:  # Validate subtitle language.
            return f"subtitle {stream.position + 1} language mismatch: expected={report_track.language}, actual={stream.language_ietf or stream.language_code}"  # Return subtitle language mismatch.
        if report_track.language_ietf != "" and stream.language_ietf != report_track.language_ietf:  # Validate precise subtitle BCP-47 language.
            return f"subtitle {stream.position + 1} BCP-47 language mismatch: expected={report_track.language_ietf}, actual={stream.language_ietf}"  # Return subtitle BCP-47 mismatch.
        target_name = resolve_subtitle_target_name(report_track, stream)  # Resolve expected subtitle name from report and forced state.
        if stream.name != target_name:  # Validate subtitle name.
            return f"subtitle {stream.position + 1} name mismatch: expected={target_name!r}, actual={stream.name!r}"  # Return subtitle name mismatch.

    return ""  # Return success marker.


def build_ffmpeg_verify_command(file_path: Path, executable: str) -> list[str]:
    """
    Build read-only FFmpeg integrity command.

    :param file_path: Media file path.
    :param executable: FFmpeg executable path.
    :return: FFmpeg command vector.
    """

    return [executable, *FFMPEG_ERROR_FLAGS, "-i", str(file_path), *FFMPEG_NULL_OUTPUT]  # Return read-only decode command.


def validate_media_integrity(file_path: Path) -> str:
    """
    Validate media readability after metadata mutation.

    :param file_path: Media file path.
    :return: Empty text when media validates, otherwise reason.
    """

    executable = find_executable("ffmpeg")  # Locate FFmpeg executable.
    if executable is None:  # Detect unavailable FFmpeg.
        return "ffmpeg not found"  # Return missing-tool reason.

    command = build_ffmpeg_verify_command(file_path, executable)  # Build read-only integrity command.
    try:  # Run FFmpeg without writing output media.
        result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="replace")  # Execute read-only decode.
    except OSError as error:  # Handle execution failure.
        return str(error)  # Return launch failure.

    if result.returncode != 0:  # Detect media validation failure.
        return (result.stderr or result.stdout).strip() or f"ffmpeg returned {result.returncode}"  # Return FFmpeg diagnostics.
    return ""  # Return success marker.


def apply_plan(plan: PlannedFileEdit, apply_changes: bool, summary: WorkflowSummary) -> None:
    """
    Apply or preview one planned file edit.

    :param plan: Planned file edit.
    :param apply_changes: Whether changes should be applied.
    :param summary: Mutable workflow summary.
    :return: None.
    """

    result = run_mkvpropedit(plan.movie.full_path, plan.edits, apply_changes)  # Run or preview mkvpropedit.
    if not result.success:  # Detect edit failure.
        summary.failed += 1  # Count edit failure.
        summary.messages.append(f"mkvpropedit failed for {plan.movie.full_path}: {result.details}")  # Store edit failure.
        return  # Stop processing this file.

    if result.setter_count == 0:  # Detect no-op after command construction.
        summary.skipped += 1  # Count no-op.
        summary.messages.append(f"No mkvpropedit setters needed for {plan.movie.full_path}")  # Store no-op message.
        return  # Stop processing this file.

    if not apply_changes:  # Detect dry-run mode.
        summary.messages.append(f"Planned {result.setter_count} setter(s) for {plan.movie.full_path}: {result.details}")  # Store dry-run message.
        return  # Skip post-mutation verification.

    if result.warning:  # Preserve MKVToolNix warning state.
        summary.warnings += 1  # Count warning-bearing edit.
        summary.messages.append(f"mkvpropedit warning for {plan.movie.full_path}: {result.details}")  # Store warning diagnostics.

    try:  # Verify post-mutation metadata.
        verification_issue = validate_expected_metadata(plan)  # Reprobe and validate expected metadata.
    except RuntimeError as error:  # Handle post-edit probe failure.
        summary.failed += 1  # Count verification failure.
        summary.messages.append(f"Post-edit probe failed for {plan.movie.full_path}: {error}")  # Store verification failure.
        return  # Stop processing this file.

    if verification_issue != "":  # Detect verification mismatch.
        summary.failed += 1  # Count verification mismatch.
        summary.messages.append(f"Post-edit verification failed for {plan.movie.full_path}: {verification_issue}")  # Store verification mismatch.
        return  # Stop processing this file.

    integrity_issue = validate_media_integrity(plan.movie.full_path)  # Run read-only media integrity validation.
    if integrity_issue != "":  # Detect media integrity failure.
        summary.failed += 1  # Count integrity failure.
        summary.messages.append(f"Post-edit integrity failed for {plan.movie.full_path}: {integrity_issue}")  # Store integrity failure.
        return  # Stop processing this file.

    summary.changed_files += 1  # Count successful changed file.
    summary.messages.append(f"Applied {result.setter_count} setter(s) to {plan.movie.full_path}")  # Store success message.


def process_movie_with_lock(movie: MovieReportEntry, summary: WorkflowSummary) -> None:
    """
    Process one movie in apply mode while holding media lock.

    :param movie: Parsed movie report entry.
    :param summary: Mutable workflow summary.
    :return: None.
    """

    support_issue = validate_file_support(movie.full_path)  # Validate media support before lock acquisition.
    if support_issue != "":  # Detect unsupported or invalid media.
        summary.skipped += 1  # Count skipped file.
        summary.messages.append(f"Skipped {movie.full_path}: {support_issue}")  # Store skip reason.
        return  # Stop processing unsupported file.

    lock_handle = acquire_media_edit_lock(movie.full_path)  # Acquire lock before probe, plan, mutation, and verification.
    try:  # Keep critical workflow inside media lock.
        plan = plan_file_edits(movie, summary)  # Rebuild validated plan from locked current metadata.
        if plan is None:  # Detect no validated plan.
            return  # Leave file untouched.
        apply_plan(plan, True, summary)  # Apply validated plan while lock remains held.
    finally:  # Release media lock after all validation.
        release_file_lock(lock_handle)  # Release media edit lock.


def resolve_report_paths(arguments: list[str]) -> list[Path]:
    """
    Resolve report paths from CLI arguments.

    :param arguments: Raw report path arguments.
    :return: Resolved report paths.
    """

    if arguments:  # Use explicit report path arguments.
        return [Path(argument).resolve(strict=False) for argument in arguments]  # Return explicit paths.
    return sorted(REPORTS_DIRECTORY.glob("*-non_english_default_audio_movies.json"), key=lambda path: path.name.casefold())  # Return default project reports.


def build_argument_parser() -> argparse.ArgumentParser:
    """
    Build the report metadata corrector argument parser.

    :return: Argument parser.
    """

    parser = argparse.ArgumentParser(description="Correct MKV audio and internal subtitle metadata from non-English default audio reports.")  # Create CLI parser.
    parser.add_argument("reports", nargs="*", help="JSON report path(s); defaults to Reports/*-non_english_default_audio_movies.json.")  # Add report path arguments.
    parser.add_argument("--apply", action="store_true", help="Apply mkvpropedit changes; omit for dry-run preview.")  # Add mutation opt-in.
    return parser  # Return parser.


def print_summary(summary: WorkflowSummary, apply_changes: bool) -> None:
    """
    Print workflow summary and messages.

    :param summary: Workflow summary.
    :param apply_changes: Whether changes were applied.
    :return: None.
    """

    mode = "apply" if apply_changes else "dry-run"  # Resolve run mode.
    summary_text = f"mode={mode}, reports={summary.reports}, files={summary.files}, planned_files={summary.planned_files}, changed_files={summary.changed_files}, planned_edits={summary.planned_edits}, warnings={summary.warnings}, skipped={summary.skipped}, failed={summary.failed}"  # Build summary text.
    print(f"\n{BackgroundColors.GREEN}Summary:{BackgroundColors.CYAN} {summary_text}{Style.RESET_ALL}")  # Print summary.
    for message in summary.messages:  # Iterate workflow messages.
        color = BackgroundColors.RED if "failed" in message.casefold() or "mismatch" in message.casefold() else BackgroundColors.YELLOW if "skipped" in message.casefold() or "unchanged" in message.casefold() else BackgroundColors.GREEN  # Resolve message color.
        print(f"{color}{message}{Style.RESET_ALL}")  # Print message.


def run_corrector_cli(arguments: list[str] | None = None) -> int:
    """
    Run the report metadata corrector CLI.

    :param arguments: Optional CLI argument list.
    :return: Process exit status.
    """

    parser = build_argument_parser()  # Build CLI parser.
    parsed_args = parser.parse_args(arguments)  # Parse CLI arguments.
    report_paths = resolve_report_paths(list(parsed_args.reports))  # Resolve report paths.
    summary = WorkflowSummary()  # Initialize workflow summary.
    if not report_paths:  # Detect missing default reports.
        print(f"{BackgroundColors.RED}No report files found.{Style.RESET_ALL}")  # Report missing reports.
        return 1  # Return failure status.

    try:  # Load report entries.
        movies = collect_report_entries(report_paths, summary)  # Parse report movie entries.
    except RuntimeError as error:  # Handle report loading failure.
        print(f"{BackgroundColors.RED}{error}{Style.RESET_ALL}")  # Print report error.
        return 1  # Return failure status.

    progress_bar = tqdm(movies, desc=f"{BackgroundColors.CYAN}Processing media{Style.RESET_ALL}", unit="file", colour="cyan", dynamic_ncols=True)  # Create colored media progress bar.
    for movie in progress_bar:  # Iterate parsed movie entries with progress.
        progress_bar.set_postfix_str(build_progress_media_path(movie), refresh=True)  # Show current relative media path inline.
        summary.files += 1  # Count processed report entry.
        if parsed_args.apply:  # Use locked apply workflow for mutations.
            process_movie_with_lock(movie, summary)  # Process one movie under media lock.
            continue  # Continue to next file.
        plan = plan_file_edits(movie, summary)  # Plan safe edits for dry-run.
        if plan is None:  # Skip files without a validated plan.
            continue  # Continue to next file.
        apply_plan(plan, bool(parsed_args.apply), summary)  # Apply or preview validated plan.

    print_summary(summary, bool(parsed_args.apply))  # Print final summary.
    return 1 if summary.failed > 0 else 0  # Return nonzero when failures occurred.


def main() -> None:
    """
    Run report metadata correction from command line.

    :return: None.
    """

    print(f"{BackgroundColors.CLEAR_TERMINAL}{BackgroundColors.BOLD}{BackgroundColors.GREEN}Welcome to the {BackgroundColors.CYAN}Report Track Metadata Corrector{BackgroundColors.GREEN} program!{Style.RESET_ALL}", end="\n\n")  # Print welcome message.
    start_time = datetime.datetime.now()  # Capture start time.
    status = run_corrector_cli()  # Run CLI workflow.
    finish_time = datetime.datetime.now()  # Capture finish time.
    elapsed_seconds = int((finish_time - start_time).total_seconds())  # Calculate elapsed seconds.
    print(f"{BackgroundColors.GREEN}Start time: {BackgroundColors.CYAN}{start_time.strftime('%d/%m/%Y - %H:%M:%S')}\n{BackgroundColors.GREEN}Finish time: {BackgroundColors.CYAN}{finish_time.strftime('%d/%m/%Y - %H:%M:%S')}\n{BackgroundColors.GREEN}Execution time: {BackgroundColors.CYAN}{elapsed_seconds}s{Style.RESET_ALL}")  # Print timing summary.
    print(f"{BackgroundColors.BOLD}{BackgroundColors.GREEN}Program finished.{Style.RESET_ALL}")  # Print completion message.
    sys.exit(status)  # Return process status.


if __name__ == "__main__":  # Run script entry point when executed directly.
    main()  # Execute CLI workflow.
