"""
================================================================================
Media File Integrity Scanner
================================================================================
Author      : Breno Farias da Silva
Created     : 2026-08-19
Description :
    Recursively scans configured movie directories for supported media files and
    detects FFmpeg-reported container, packet, and structural integrity errors.
    Every file is read from beginning to end without re-encoding or producing a
    media output, allowing recoverable errors such as malformed Matroska/EBML
    elements to be reported even when FFmpeg itself exits successfully.

    Key features include:
        - Recursive scanning across multiple configured movie root directories.
        - Support for common MKV, MP4, AVI, MOV, WebM, MPEG, TS, and related formats.
        - Full-file FFmpeg packet-read validation without creating or modifying media.
        - Detection of recoverable FFmpeg errors even when the process exit code is 0.
        - One incrementally updated JSON corruption report per configured input root.
        - Collision-safe report names derived from each input path.
        - Unix-style forward-slash path serialization in reports and terminal output.
        - Bounded error storage to prevent heavily corrupted files from bloating reports.

Usage:
    1. Configure INPUT_DIRS, FFMPEG, MEDIA_EXTENSIONS, and MAX_ERROR_LINES_PER_FILE.
    2. Ensure FFmpeg is installed and available through FFMPEG or the system PATH.
    3. Execute the script through the project Makefile or directly with Python:
        $ make run   or   $ python main.py
    4. Review the generated JSON reports inside ./Outputs/ after or during the scan.

Outputs:
    - ./Outputs/E-Movies-report.json for the configured E:/Movies/ input directory.
    - ./Outputs/F-Movies-report.json for the configured F:/Movies/ input directory.
    - ./Logs/<script_name>.log containing the terminal output generated by the scan.

TODOs:
    - Add an optional full audio/video decode mode for codec-level corruption checks.
    - Add resumable scan state for very large media libraries interrupted mid-file.
    - Add optional controlled parallelism for media stored on independent drives.

Dependencies:
    - Python >= 3.10.
    - FFmpeg available through the configured FFMPEG command or executable path.
    - colorama.
    - tqdm.
    - Project Logger module.

Assumptions & Notes:
    - INPUT_DIRS are recursively scanned and media files are never modified.
    - The default packet-read scan is designed to detect container/packet errors such
      as Matroska EBML corruption without the CPU cost of decoding every video frame.
    - FFmpeg is executed with error-only logging; any emitted error line marks the
      media file as corrupted/suspicious even when FFmpeg returns exit code 0.
    - Codec bitstream damage that only becomes visible during decoding may require the
      future optional full-decode mode and is outside the default packet-read scan.
    - Reports are rewritten atomically after each scanned file so completed results
      remain available if the program is interrupted later in the library.
    - Paths written to reports or terminal output always use forward slashes, while
      native Path objects remain unchanged for actual filesystem operations.
"""

import atexit  # For playing a sound when the program finishes
import datetime  # For getting the current date and time
import json  # For writing corruption reports as JSON files
import os  # For running a command in the terminal and recursively walking directories
import platform  # For getting the operating system name
import re  # For sanitizing input directory paths into report filenames
import shutil  # For resolving the configured FFmpeg executable
import subprocess  # For running FFmpeg integrity scans
import sys  # For system-specific parameters and functions
from colorama import Style  # For coloring the terminal
from Logger import Logger  # For logging output to both terminal and file
from pathlib import Path  # For handling file paths
from tqdm import tqdm  # For inline per-input-directory scan progress


# Macros:
class BackgroundColors:  # Colors for the terminal
    CYAN = "\033[96m"  # Cyan
    GREEN = "\033[92m"  # Green
    YELLOW = "\033[93m"  # Yellow
    RED = "\033[91m"  # Red
    BOLD = "\033[1m"  # Bold
    UNDERLINE = "\033[4m"  # Underline
    CLEAR_TERMINAL = "\033[H\033[J"  # Clear the terminal


# Execution Constants:
VERBOSE = False  # Set to True to output verbose messages
INPUT_DIRS = [f"E:/Movies/", f"F:/Documentaries/", f"F:/Movies/", f"F:/Series/", f"G:/Animes/", f"G:/Series/"]  # Root directories recursively scanned for movie directories
OUTPUT_DIR = Path("./Outputs/")  # Directory receiving one JSON corruption report for each configured input root
FFMPEG = "ffmpeg"  # FFmpeg executable name or full path used for integrity scans
MAX_ERROR_LINES_PER_FILE = 500  # Maximum FFmpeg error lines retained per corrupted media file in the JSON report
MEDIA_EXTENSIONS = {  # Supported movie and video container extensions scanned recursively
    ".3g2",  # 3GPP2 multimedia container
    ".3gp",  # 3GPP multimedia container
    ".avi",  # Audio Video Interleave container
    ".flv",  # Flash Video container
    ".m2ts",  # Blu-ray MPEG-2 transport stream container
    ".m4v",  # MPEG-4 video container
    ".mkv",  # Matroska video container
    ".mk3d",  # Matroska stereoscopic video container
    ".mov",  # QuickTime movie container
    ".mp4",  # MPEG-4 Part 14 container
    ".mpeg",  # MPEG program stream container
    ".mpg",  # MPEG program stream container
    ".mts",  # AVCHD MPEG transport stream container
    ".ogv",  # Ogg video container
    ".ts",  # MPEG transport stream container
    ".vob",  # DVD video object container
    ".webm",  # WebM media container
    ".wmv",  # Windows Media Video container
}

# Logger Setup:
logger = Logger(f"./Logs/{Path(__file__).stem}.log", clean=True)  # Create a Logger instance
sys.stdout = logger  # Redirect stdout to the logger
sys.stderr = logger  # Redirect stderr to the logger

# Sound Constants:
SOUND_COMMANDS = {
    "Darwin": "afplay",
    "Linux": "aplay",
    "Windows": "start",
}  # The commands to play a sound for each operating system
SOUND_FILE = "./.assets/Sounds/NotificationSound.wav"  # The path to the sound file

# RUN_FUNCTIONS:
RUN_FUNCTIONS = {
    "Play Sound": True,  # Set to True to play a sound when the program finishes
}

# Functions Definitions:


def unix_path(path_value: str | Path) -> str:
    """
    Convert a path-like value to a platform-independent forward-slash representation.

    :param path_value: Path or path string being serialized or displayed.
    :return: Path text using forward slashes regardless of the current operating system.
    """

    return str(path_value).replace("\\", "/")  # Normalize Windows path separators only for reports, logs, and other user-visible text


def verbose_output(true_string="", false_string=""):
    """
    Outputs a message if the VERBOSE constant is set to True.

    :param true_string: The string to be outputted if the VERBOSE constant is set to True.
    :param false_string: The string to be outputted if the VERBOSE constant is set to False.
    :return: None
    """

    if VERBOSE and true_string != "":  # If VERBOSE is True and a true_string was provided
        print(true_string)  # Output the true statement string
    elif false_string != "":  # If a false_string was provided
        print(false_string)  # Output the false statement string


def resolve_entry_with_trailing_space(current_path: str, entry: str, stripped_part: str) -> str:
    """
    Resolve and optionally rename a directory entry with trailing spaces.

    :param current_path: Current directory path.
    :param entry: Directory entry name.
    :param stripped_part: Normalized target name without surrounding spaces.
    :return: Resolved path after optional rename.
    """

    try:  # Wrap full function logic to ensure safe execution
        resolved = os.path.join(current_path, entry)  # Build resolved path

        if entry != stripped_part:  # Verify trailing spaces exist
            corrected = os.path.join(current_path, stripped_part)  # Build corrected path
            try:  # Attempt to rename entry
                os.rename(resolved, corrected)  # Rename entry to stripped version
                verbose_output(true_string=f"{BackgroundColors.GREEN}Renamed: {BackgroundColors.CYAN}{unix_path(resolved)}{BackgroundColors.GREEN} -> {BackgroundColors.CYAN}{unix_path(corrected)}{Style.RESET_ALL}")  # Log rename
                resolved = corrected  # Update resolved path after rename
            except Exception:  # Handle rename failure
                verbose_output(true_string=f"{BackgroundColors.RED}Failed to rename: {BackgroundColors.CYAN}{unix_path(resolved)}{Style.RESET_ALL}")  # Log failure

        return resolved  # Return resolved path
    except Exception:  # Catch unexpected errors
        return os.path.join(current_path, entry)  # Return fallback resolved path


def resolve_full_trailing_space_path(filepath: str) -> str:
    """
    Resolve trailing space issues across all path components.

    :param filepath: Path to resolve potential trailing space mismatches.
    :return: Corrected full path if matches are found, otherwise original filepath.
    """

    try:  # Wrap full function logic to ensure safe execution
        verbose_output(true_string=f"{BackgroundColors.GREEN}Resolving full trailing space path for: {BackgroundColors.CYAN}{unix_path(filepath)}{Style.RESET_ALL}")  # Log start

        if not isinstance(filepath, str) or not filepath:  # Verify filepath validity
            verbose_output(true_string=f"{BackgroundColors.YELLOW}Invalid filepath provided, skipping resolution.{Style.RESET_ALL}")  # Log invalid input
            return filepath  # Return original

        filepath = os.path.expanduser(filepath)  # Expand ~ to user directory
        parts = filepath.split(os.sep)  # Split path into components

        if not parts:  # Verify path parts exist
            return filepath  # Return original

        if filepath.startswith(os.sep):  # Handle absolute paths
            current_path = os.sep  # Start from root
            parts = parts[1:]  # Remove empty root part
        else:
            current_path = parts[0] if parts[0] else os.getcwd()  # Initialize base
            parts = parts[1:] if parts[0] else parts  # Adjust parts

        for part in parts:  # Iterate over each path component
            if part == "":  # Skip empty parts
                continue  # Continue iteration

            try:  # Attempt to list current directory
                entries = os.listdir(current_path) if os.path.isdir(current_path) else []  # List current directory entries
            except Exception:  # Handle failure to list directory contents
                verbose_output(true_string=f"{BackgroundColors.RED}Failed to list directory: {BackgroundColors.CYAN}{unix_path(current_path)}{Style.RESET_ALL}")  # Log failure
                return filepath  # Return original

            stripped_part = part.strip()  # Normalize current part
            match_found = False  # Initialize match flag

            for entry in entries:  # Iterate directory entries
                try:  # Attempt safe comparison for each entry
                    if entry.strip() == stripped_part:  # Compare stripped names
                        current_path = resolve_entry_with_trailing_space(current_path, entry, stripped_part)  # Resolve entry and update current path
                        match_found = True  # Mark match
                        break  # Stop searching
                except Exception:  # Handle any unexpected error during comparison
                    continue  # Continue on error

            if not match_found:  # If no match found for this segment
                verbose_output(true_string=f"{BackgroundColors.YELLOW}No match for segment: {BackgroundColors.CYAN}{part}{Style.RESET_ALL}")  # Log miss
                return filepath  # Return original

        return current_path  # Return fully resolved path

    except Exception:  # Catch unexpected errors to maintain stability
        verbose_output(true_string=f"{BackgroundColors.RED}Error resolving full path: {BackgroundColors.CYAN}{unix_path(filepath)}{Style.RESET_ALL}")  # Log error
        return filepath  # Return original


def verify_filepath_exists(filepath):
    """
    Verify if a file or folder exists at the specified path.

    :param filepath: Path to the file or folder
    :return: True if the file or folder exists, False otherwise
    """

    try:  # Wrap full function logic to ensure production-safe monitoring
        verbose_output(
            f"{BackgroundColors.GREEN}Verifying if the file or folder exists at the path: {BackgroundColors.CYAN}{unix_path(filepath)}{Style.RESET_ALL}"
        )  # Output the verbose message
        
        if not isinstance(filepath, str) or not filepath.strip():  # Verify for non-string or empty/whitespace-only input   
            verbose_output(true_string=f"{BackgroundColors.YELLOW}Invalid filepath provided, skipping existence verification.{Style.RESET_ALL}")  # Log invalid input
            return False  # Return False for invalid input

        if os.path.exists(filepath):  # Fast path: original input exists
            return True  # Return True immediately

        candidate = str(filepath).strip()  # Normalize input to string and strip surrounding whitespace

        if (candidate.startswith("'") and candidate.endswith("'")) or (
            candidate.startswith('"') and candidate.endswith('"')
        ):  # Handle quoted paths from config files
            candidate = candidate[1:-1].strip()  # Remove wrapping quotes and trim again

        candidate = os.path.expanduser(candidate)  # Expand ~ to user home directory
        candidate = os.path.normpath(candidate)  # Normalize path separators and structure

        if os.path.exists(candidate):  # Verify normalized candidate directly
            return True  # Return True if normalized path exists

        repo_dir = os.path.dirname(os.path.abspath(__file__))  # Resolve repository directory
        cwd = os.getcwd()  # Capture current working directory

        alt = candidate.lstrip(os.sep) if candidate.startswith(os.sep) else candidate  # Prepare relative-safe path

        repo_candidate = os.path.join(repo_dir, alt)  # Build repo-relative candidate
        cwd_candidate = os.path.join(cwd, alt)  # Build cwd-relative candidate

        for path_variant in (repo_candidate, cwd_candidate):  # Iterate alternative base paths
            try:
                normalized_variant = os.path.normpath(path_variant)  # Normalize variant
                if os.path.exists(normalized_variant):  # Verify existence
                    return True  # Return True if found
            except Exception:
                continue  # Continue safely on error

        try:  # Attempt absolute path resolution as fallback
            abs_candidate = os.path.abspath(candidate)  # Build absolute path
            if os.path.exists(abs_candidate):  # Verify existence
                return True  # Return True if found
        except Exception:
            pass  # Ignore resolution errors

        for path_variant in (candidate, repo_candidate, cwd_candidate):  # Attempt trailing-space resolution on all variants
            try:  # Attempt to resolve trailing space issues across path components for this variant
                resolved = resolve_full_trailing_space_path(path_variant)  # Resolve trailing space issues across path components
                if resolved != path_variant and os.path.exists(resolved):  # Verify resolved path exists
                    verbose_output(
                        f"{BackgroundColors.YELLOW}Resolved trailing space mismatch: {BackgroundColors.CYAN}{unix_path(path_variant)}{BackgroundColors.YELLOW} -> {BackgroundColors.CYAN}{unix_path(resolved)}{Style.RESET_ALL}"
                    )  # Log successful resolution
                    return True  # Return True if corrected path exists
            except Exception:  # Catch any exception during trailing space resolution   
                continue  # Continue safely on error

        return False  # Not found after all resolution strategies
    except Exception as e:  # Catch any exception to ensure logging and Telegram alert
        print(str(e))  # Print error to terminal for server logs
        raise  # Re-raise to preserve original failure semantics



def resolve_ffmpeg_executable() -> str:
    """
    Resolve the configured FFmpeg executable before starting expensive media scans.

    :return: Resolved FFmpeg executable path or command path.
    """

    configured_path = Path(FFMPEG)  # Interpret the configured FFmpeg value as a possible direct filesystem path

    if configured_path.is_file():  # Prefer an explicitly configured executable file when it exists
        return str(configured_path)  # Return the direct FFmpeg executable path

    resolved_path = shutil.which(FFMPEG)  # Search the operating system PATH for the configured FFmpeg command

    if resolved_path is None:  # Reject execution when FFmpeg cannot be located
        raise FileNotFoundError(f"FFmpeg executable not found: {unix_path(FFMPEG)}")  # Report the missing external dependency

    return resolved_path  # Return the executable path discovered through the system PATH


def build_report_filepath(input_dir: str) -> Path:
    """
    Build a filesystem-compatible JSON report path derived from an input directory.

    :param input_dir: Configured input root used as the report filename source.
    :return: Report path inside OUTPUT_DIR.
    """

    normalized_input = str(input_dir).strip().rstrip("/\\")  # Remove surrounding whitespace and trailing path separators
    report_name = re.sub(r"[\\/]+", "-", normalized_input)  # Replace directory separators with hyphens as requested
    report_name = re.sub(r'[:*?"<>|]+', "-", report_name)  # Replace Windows-invalid filename characters such as the drive colon
    report_name = re.sub(r"-+", "-", report_name).strip("-")  # Collapse repeated hyphens and remove edge separators

    if not report_name:  # Protect against an input path that sanitizes to an empty filename
        report_name = "media"  # Use a deterministic fallback report name

    return OUTPUT_DIR / f"{report_name}-report.json"  # Append the requested report suffix inside the output directory


def discovery_error_record(error: OSError) -> dict:
    """
    Convert an os.walk directory traversal error into a JSON-serializable record.

    :param error: Directory traversal exception received from os.walk.
    :return: Dictionary describing the discovery failure.
    """

    return {  # Build the directory discovery error record
        "path": unix_path(getattr(error, "filename", "") or ""),  # Preserve the affected filesystem path using the required Unix-style separators
        "error_type": type(error).__name__,  # Record the concrete operating system exception type
        "message": unix_path(str(error)),  # Preserve the traversal failure message while normalizing any embedded Windows path separators
    }


def discover_media_files(input_dir: Path) -> tuple[list[Path], list[dict]]:
    """
    Recursively discover supported media files under one configured input directory.

    :param input_dir: Root directory recursively scanned for supported media files.
    :return: Sorted media file list and directory discovery error records.
    """

    media_files: list[Path] = []  # Store supported media files discovered below the current input root
    discovery_errors: list[dict] = []  # Store directory traversal failures without aborting the remaining scan

    def handle_walk_error(error: OSError) -> None:
        """
        Record one os.walk traversal error while allowing scanning to continue.

        :param error: Directory traversal exception received from os.walk.
        :return: None
        """

        discovery_errors.append(discovery_error_record(error))  # Preserve the traversal problem in the generated JSON report
        logger.write(f"{BackgroundColors.YELLOW}Directory discovery error: {BackgroundColors.CYAN}{unix_path(str(error))}{Style.RESET_ALL}")  # Report the inaccessible directory in the terminal log

    for current_path, _, filenames in os.walk(input_dir, onerror=handle_walk_error):  # Traverse every accessible subdirectory without following directory symlinks
        for filename in filenames:  # Inspect every file discovered in the current directory
            media_path = Path(current_path) / filename  # Build the complete media candidate path

            if media_path.suffix.lower() not in MEDIA_EXTENSIONS:  # Ignore files outside the configured media extension set
                continue  # Continue with the next discovered file

            media_files.append(media_path)  # Add the supported media file to the scan queue

    return sorted(media_files, key=lambda path: str(path).casefold()), discovery_errors  # Return deterministic case-insensitive scan ordering and traversal errors


def relative_media_path(media_path: Path, input_dir: Path) -> str:
    """
    Return a report-friendly media path relative to its configured input root.

    :param media_path: Media file being represented in the JSON report.
    :param input_dir: Configured root directory containing the media file.
    :return: Relative media path when possible, otherwise the absolute media path.
    """

    try:  # Attempt normal relative path resolution for files found below the configured root
        return unix_path(media_path.relative_to(input_dir))  # Return the concise root-relative media path using Unix-style separators
    except ValueError:  # Handle unusual path normalization differences that prevent relative resolution
        return unix_path(media_path)  # Fall back to the complete media path using Unix-style separators


def build_integrity_scan_command(ffmpeg_executable: str, media_path: Path) -> list[str]:
    """
    Build an FFmpeg command that reads every mapped media packet without re-encoding.

    :param ffmpeg_executable: Resolved FFmpeg executable path.
    :param media_path: Media file scanned for integrity problems.
    :return: Complete FFmpeg argument list for a full-file packet-read scan.
    """

    return [  # Build the complete non-destructive FFmpeg integrity command
        ffmpeg_executable,  # Use the resolved FFmpeg executable
        "-hide_banner",  # Suppress the FFmpeg build banner from scan output
        "-nostdin",  # Prevent FFmpeg from consuming terminal input during long scans
        "-v",  # Configure FFmpeg log verbosity
        "error",  # Emit only error-level messages so warnings are not treated as corruption
        "-i",  # Declare the media input file
        str(media_path),  # Supply the complete path of the media file being scanned
        "-map",  # Explicitly map streams into the null output
        "0",  # Map every stream from the input so packet traversal is not limited to the default streams
        "-c",  # Configure the codec policy for all mapped streams
        "copy",  # Copy packets without decoding or re-encoding while still reading the complete source file
        "-f",  # Select the output muxer
        "null",  # Discard mapped packets instead of creating a media output file
        "-",  # Send the null muxer to standard output, which is itself discarded by the Python process
    ]


def scan_media_file(ffmpeg_executable: str, media_path: Path, input_dir: Path) -> dict:
    """
    Scan one media file from beginning to end and capture FFmpeg integrity errors.

    :param ffmpeg_executable: Resolved FFmpeg executable path.
    :param media_path: Media file scanned for corruption or structural errors.
    :param input_dir: Configured input root used for relative report paths.
    :return: Dictionary describing the scan result for the media file.
    """

    command = build_integrity_scan_command(ffmpeg_executable, media_path)  # Build the complete FFmpeg packet-read integrity command
    error_lines: list[str] = []  # Store a bounded set of FFmpeg error messages for the current media file
    total_error_lines = 0  # Count every non-empty FFmpeg error line even after report storage reaches its configured limit
    scan_start_time = datetime.datetime.now()  # Capture the current file scan start time

    process = subprocess.Popen(  # Start FFmpeg and stream its error output incrementally to avoid unbounded memory usage
        command,  # Supply the prepared integrity scan command
        stdout=subprocess.DEVNULL,  # Discard null-muxer standard output because no media artifact is produced
        stderr=subprocess.PIPE,  # Capture FFmpeg error-level output for corruption detection
        text=True,  # Decode FFmpeg stderr into Python strings
        encoding="utf-8",  # Decode FFmpeg output consistently as UTF-8
        errors="replace",  # Replace malformed terminal bytes rather than failing the corruption scan
    )

    if process.stderr is None:  # Guard against an unexpected subprocess configuration without a stderr pipe
        process.kill()  # Stop the unusable FFmpeg process before reporting the internal scan failure
        raise RuntimeError(f"Could not capture FFmpeg stderr for: {unix_path(media_path)}")  # Reject a scan that cannot observe integrity errors

    for stderr_line in process.stderr:  # Read FFmpeg error output continuously until the complete media file has been consumed
        clean_line = unix_path(stderr_line.rstrip("\r\n"))  # Remove terminal line endings and normalize any FFmpeg-reported Windows paths to Unix-style separators

        if not clean_line.strip():  # Ignore empty FFmpeg output lines that do not describe an integrity problem
            continue  # Continue waiting for the next emitted error line

        total_error_lines += 1  # Count the detected FFmpeg error regardless of whether it is retained in the bounded JSON details

        if len(error_lines) < MAX_ERROR_LINES_PER_FILE:  # Retain detailed errors only until the configured per-file report limit is reached
            error_lines.append(clean_line)  # Preserve the FFmpeg error line exactly as emitted apart from its newline

    return_code = process.wait()  # Wait for FFmpeg termination and capture its final process exit code
    scan_finish_time = datetime.datetime.now()  # Capture the current file scan completion time
    has_integrity_error = total_error_lines > 0 or return_code != 0  # Treat emitted error lines or an unsuccessful FFmpeg exit as an integrity problem

    try:  # Attempt to capture the current media file size for report diagnostics
        file_size_bytes = media_path.stat().st_size  # Read the media file size without modifying the source file
    except OSError:  # Handle files removed or made inaccessible after discovery
        file_size_bytes = None  # Preserve the unavailable file size explicitly in the JSON report

    return {  # Build the complete per-file integrity scan result
        "file_path": unix_path(media_path),  # Store the complete source media path using Unix-style separators
        "relative_path": relative_media_path(media_path, input_dir),  # Store a concise path relative to the configured input root
        "extension": media_path.suffix.lower(),  # Record the normalized media container extension
        "file_size_bytes": file_size_bytes,  # Record the media file size when available
        "status": "corrupt" if has_integrity_error else "clean",  # Classify the file from FFmpeg's error output and exit status
        "ffmpeg_exit_code": return_code,  # Preserve FFmpeg's exit status because recoverable corruption may still return zero
        "error_line_count": total_error_lines,  # Record the complete number of FFmpeg error lines detected
        "errors_truncated": total_error_lines > len(error_lines),  # Indicate whether only the first configured error lines were retained
        "errors": error_lines,  # Preserve the bounded FFmpeg integrity error details
        "scan_started_at": scan_start_time.isoformat(timespec="seconds"),  # Record when scanning of this file began
        "scan_finished_at": scan_finish_time.isoformat(timespec="seconds"),  # Record when scanning of this file completed
        "scan_execution_time": calculate_execution_time(scan_start_time, scan_finish_time),  # Store a human-readable duration for this file scan
    }


def write_json_report(report_path: Path, report_data: dict) -> None:
    """
    Atomically write a JSON integrity report so interruptions do not leave partial JSON.

    :param report_path: Final JSON report path.
    :param report_data: JSON-serializable report dictionary.
    :return: None
    """

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)  # Ensure the configured output directory exists before writing reports
    temporary_path = report_path.with_suffix(f"{report_path.suffix}.tmp")  # Build a temporary path beside the final report for atomic replacement

    with temporary_path.open("w", encoding="utf-8") as report_file:  # Create or replace the temporary UTF-8 JSON report file
        json.dump(report_data, report_file, ensure_ascii=False, indent=4)  # Serialize readable Unicode JSON with stable indentation
        report_file.write("\n")  # Finish the JSON document with a conventional trailing newline

    os.replace(temporary_path, report_path)  # Atomically replace the previous report with the fully written temporary document


def build_initial_report(input_dir_string: str, input_dir: Path, report_path: Path, discovery_errors: list[dict], total_media_files: int) -> dict:
    """
    Build the initial JSON report structure before individual media scans begin.

    :param input_dir_string: Original configured input directory string.
    :param input_dir: Normalized input root path used for scanning.
    :param report_path: Destination JSON report path.
    :param discovery_errors: Directory traversal failures collected during discovery.
    :param total_media_files: Number of supported media files queued for scanning.
    :return: Initial report dictionary.
    """

    current_time = datetime.datetime.now()  # Capture the report initialization time

    return {  # Build the complete initial report document
        "input_dir": unix_path(input_dir_string),  # Store the configured input directory using Unix-style separators
        "resolved_input_dir": unix_path(input_dir),  # Record the normalized filesystem root using Unix-style separators
        "report_file": unix_path(report_path),  # Record the generated JSON report path using Unix-style separators
        "scan_method": "FFmpeg full-file packet-read scan using -v error -map 0 -c copy -f null -",  # Document the non-destructive validation strategy
        "supported_extensions": sorted(MEDIA_EXTENSIONS),  # Record every configured media extension considered during recursive discovery
        "status": "in_progress",  # Mark the report as incomplete while media files are still being processed
        "scan_started_at": current_time.isoformat(timespec="seconds"),  # Record when processing of this input root began
        "scan_finished_at": None,  # Leave the completion timestamp unset until the entire input root has been scanned
        "scan_execution_time": None,  # Leave the final input-root duration unset until processing completes
        "total_media_files": total_media_files,  # Record the number of supported files discovered before scanning starts
        "files_scanned": 0,  # Count media files whose FFmpeg scans have completed
        "clean_files": 0,  # Count files that emit no FFmpeg errors and return successfully
        "corrupted_files": 0,  # Count files with FFmpeg error output or an unsuccessful FFmpeg exit code
        "scan_failures": 0,  # Count Python/subprocess failures that prevent an integrity result from being obtained
        "discovery_errors": discovery_errors,  # Preserve inaccessible directory errors encountered during recursive discovery
        "corruptions": [],  # Store details only for files classified as corrupted or suspicious
        "failed_scans": [],  # Store media files that could not be scanned to completion by the Python workflow
    }


def failed_scan_record(media_path: Path, input_dir: Path, exception: Exception) -> dict:
    """
    Build a JSON record for a media file that could not be scanned to completion.

    :param media_path: Media file whose integrity scan failed unexpectedly.
    :param input_dir: Configured input root used for relative report paths.
    :param exception: Exception that prevented the integrity scan from completing.
    :return: JSON-serializable failed scan record.
    """

    return {  # Build the scan failure record
        "file_path": unix_path(media_path),  # Store the complete affected media path using Unix-style separators
        "relative_path": relative_media_path(media_path, input_dir),  # Store the path relative to the configured input root when possible
        "error_type": type(exception).__name__,  # Record the concrete Python/subprocess exception type
        "message": unix_path(str(exception)),  # Preserve the scan failure description while normalizing any embedded Windows path separators
    }


def finalize_report(report_data: dict, report_start_time: datetime.datetime) -> None:
    """
    Mark an input-root report as completed and calculate its final execution time.

    :param report_data: Mutable report dictionary being finalized.
    :param report_start_time: Datetime captured immediately before input-root processing began.
    :return: None
    """

    finish_time = datetime.datetime.now()  # Capture the input-root scan completion time
    report_data["status"] = "completed"  # Mark the report as fully processed
    report_data["scan_finished_at"] = finish_time.isoformat(timespec="seconds")  # Record the final completion timestamp
    report_data["scan_execution_time"] = calculate_execution_time(report_start_time, finish_time)  # Store the complete input-root scan duration


def update_reports_with_global_corruption_summary(report_summaries: list[dict[str, int | str | Path]]) -> None:
    """
    Update every generated JSON report with cross-input corruption totals.

    :param report_summaries: Successful per-input report metadata collected during the run.
    :return: None
    """

    corrupted_files_by_input_dir = {  # Build the per-input corruption summary using normalized path strings as keys.
        unix_path(str(report_summary["input_dir"])): int(report_summary["corrupted_files"])  # Preserve one corruption count for each successfully scanned input root.
        for report_summary in report_summaries
    }  # Close the per-input corruption summary mapping.
    total_corrupted_files = sum(corrupted_files_by_input_dir.values())  # Sum every successful input-root corruption count into one global total.

    for report_summary in report_summaries:  # Rewrite every generated report so each one contains the same global corruption summary.
        report_path = Path(report_summary["report_path"])  # Resolve the current report path from the stored run summary.

        with report_path.open("r", encoding="utf-8") as report_file:  # Read the already-generated JSON report.
            report_data = json.load(report_file)  # Load the current report document before appending the cross-input summary.

        report_data["corrupted_files_by_input_dir"] = corrupted_files_by_input_dir  # Store the corruption count for each successfully scanned input root.
        report_data["total_corrupted_files_all_input_dirs"] = total_corrupted_files  # Store the total corrupted-file count across all successful input roots in this run.
        write_json_report(report_path, report_data)  # Rewrite the report atomically with the appended global totals.


def scan_input_directory(ffmpeg_executable: str, input_dir_string: str) -> dict[str, int | str | Path]:
    """
    Recursively scan one configured input root and maintain its JSON corruption report.

    :param ffmpeg_executable: Resolved FFmpeg executable path.
    :param input_dir_string: Configured input directory string to scan recursively.
    :return: Generated JSON report metadata for final cross-input summaries.
    """

    report_start_time = datetime.datetime.now()  # Capture the input-root processing start time
    input_dir = Path(input_dir_string).expanduser()  # Normalize the configured input root into a Path object
    report_path = build_report_filepath(input_dir_string)  # Build the requested path-derived JSON report filename

    if not input_dir.is_dir():  # Reject missing paths and non-directory input roots before recursive discovery
        raise NotADirectoryError(f"Input directory does not exist or is not a directory: {unix_path(input_dir)}")  # Report the invalid configured input root

    logger.write(f"{BackgroundColors.BOLD}{BackgroundColors.GREEN}Discovering media files in: {BackgroundColors.CYAN}{unix_path(input_dir)}{Style.RESET_ALL}")  # Announce recursive discovery for the current input root
    logger.write("")  # Keep one blank line before the discovery result
    media_files, discovery_errors = discover_media_files(input_dir)  # Discover every supported media file and preserve traversal failures
    report_data = build_initial_report(input_dir_string, input_dir, report_path, discovery_errors, len(media_files))  # Initialize the root-specific JSON report
    write_json_report(report_path, report_data)  # Persist the initial report before the potentially long media scan begins

    logger.write(f"{BackgroundColors.GREEN}Found {BackgroundColors.CYAN}{len(media_files)}{BackgroundColors.GREEN} supported media files.{Style.RESET_ALL}")  # Report the number of files queued for integrity scanning
    logger.write(f"{BackgroundColors.GREEN}Report: {BackgroundColors.CYAN}{unix_path(report_path)}{Style.RESET_ALL}")  # Display the JSON report destination
    logger.write("")  # Keep one blank line before the progress bar

    progress_bar = tqdm(media_files, total=len(media_files), unit="file", dynamic_ncols=True, file=sys.__stdout__, colour="green")  # Render one green inline-updated progress bar for this input directory

    for media_path in progress_bar:  # Process supported media files sequentially in deterministic path order
        progress_bar.set_description(f"{BackgroundColors.GREEN}Scanning: {BackgroundColors.CYAN}{media_path.name}{BackgroundColors.GREEN}")  # Keep hardcoded progress text green and the current filename cyan

        try:  # Isolate per-file failures so one unreadable media file does not abort the remaining library scan
            scan_result = scan_media_file(ffmpeg_executable, media_path, input_dir)  # Read the complete media file through FFmpeg and capture integrity errors
            report_data["files_scanned"] += 1  # Count the completed FFmpeg integrity scan

            if scan_result["status"] == "corrupt":  # Handle media files with FFmpeg error output or a non-zero exit code
                report_data["corrupted_files"] += 1  # Increment the corrupted/suspicious media count
                report_data["corruptions"].append(scan_result)  # Preserve full diagnostics for the affected media file
                progress_bar.clear()  # Clear the inline bar before permanent error messages
                logger.write(f"{BackgroundColors.RED}Corruption/error detected: {BackgroundColors.CYAN}{unix_path(media_path)}{Style.RESET_ALL}")  # Highlight the detected integrity issue in the terminal log
                logger.write(f"{BackgroundColors.RED}FFmpeg exit code: {BackgroundColors.CYAN}{scan_result['ffmpeg_exit_code']}{BackgroundColors.RED} | Error lines: {BackgroundColors.CYAN}{scan_result['error_line_count']}{Style.RESET_ALL}")  # Summarize FFmpeg's result without assuming non-zero exit is required for corruption
                progress_bar.refresh()  # Restore the inline bar after the permanent messages
            else:  # Handle media files that complete without FFmpeg error-level output
                report_data["clean_files"] += 1  # Increment the clean media count
                verbose_output(true_string=f"{BackgroundColors.GREEN}No FFmpeg integrity errors detected: {BackgroundColors.CYAN}{unix_path(media_path)}{Style.RESET_ALL}")  # Log clean results only in verbose mode

        except Exception as exception:  # Capture Python or subprocess failures that prevent a reliable FFmpeg integrity result
            report_data["scan_failures"] += 1  # Increment the failed scan count separately from confirmed corruption results
            report_data["failed_scans"].append(failed_scan_record(media_path, input_dir, exception))  # Preserve failure details in the JSON report
            progress_bar.clear()  # Clear the inline bar before permanent failure messages
            logger.write(f"{BackgroundColors.RED}Failed to scan: {BackgroundColors.CYAN}{unix_path(media_path)}{Style.RESET_ALL}")  # Report the affected media path
            logger.write(f"{BackgroundColors.RED}{type(exception).__name__}: {BackgroundColors.CYAN}{unix_path(str(exception))}{Style.RESET_ALL}")  # Report the concrete failure reason
            progress_bar.refresh()  # Restore the inline bar after the permanent messages

        write_json_report(report_path, report_data)  # Atomically checkpoint the report after every media file for interruption resilience

    progress_bar.close()  # Finish the current input-directory progress bar cleanly

    finalize_report(report_data, report_start_time)  # Mark the input-root report complete and calculate its final duration
    write_json_report(report_path, report_data)  # Persist the completed report state after every queued media file has been handled

    logger.write(  # Output the final input-root scan summary
        f"{BackgroundColors.GREEN}Finished input directory: {BackgroundColors.CYAN}{unix_path(input_dir)}\n"
        f"{BackgroundColors.GREEN}Scanned: {BackgroundColors.CYAN}{report_data['files_scanned']}{BackgroundColors.GREEN} | "
        f"Clean: {BackgroundColors.CYAN}{report_data['clean_files']}{BackgroundColors.GREEN} | "
        f"Corrupted: {BackgroundColors.CYAN}{report_data['corrupted_files']}{BackgroundColors.GREEN} | "
        f"Failures: {BackgroundColors.CYAN}{report_data['scan_failures']}{Style.RESET_ALL}"
    )  # Display final counts for the current input root
    logger.write("")  # Keep one blank line before the next input directory

    return {  # Return the completed report metadata for cross-input aggregation after every root finishes.
        "input_dir": unix_path(input_dir),  # Preserve the scanned input-root path using Unix-style separators.
        "report_path": report_path,  # Preserve the generated report path for later JSON updates.
        "corrupted_files": report_data["corrupted_files"],  # Preserve the final corruption count for this input root.
    }

def to_seconds(obj):
    """
    Converts various time-like objects to seconds.
    
    :param obj: The object to convert (can be int, float, timedelta, datetime, etc.)
    :return: The equivalent time in seconds as a float, or None if conversion fails
    """
    
    if obj is None:  # None can't be converted
        return None  # Signal failure to convert
    if isinstance(obj, (int, float)):  # Already numeric (seconds or timestamp)
        return float(obj)  # Return as float seconds
    if hasattr(obj, "total_seconds"):  # Timedelta-like objects
        try:  # Attempt to call total_seconds()
            return float(obj.total_seconds())  # Use the total_seconds() method
        except Exception:
            pass  # Fallthrough on error
    if hasattr(obj, "timestamp"):  # Datetime-like objects
        try:  # Attempt to call timestamp()
            return float(obj.timestamp())  # Use timestamp() to get seconds since epoch
        except Exception:
            pass  # Fallthrough on error
    return None  # Couldn't convert


def calculate_execution_time(start_time, finish_time=None):
    """
    Calculates the execution time and returns a human-readable string.

    Accepts either:
    - Two datetimes/timedeltas: `calculate_execution_time(start, finish)`
    - A single timedelta or numeric seconds: `calculate_execution_time(delta)`
    - Two numeric timestamps (seconds): `calculate_execution_time(start_s, finish_s)`

    Returns a string like "1h 2m 3s".
    """

    if finish_time is None:  # Single-argument mode: start_time already represents duration or seconds
        total_seconds = to_seconds(start_time)  # Try to convert provided value to seconds
        if total_seconds is None:  # Conversion failed
            try:  # Attempt numeric coercion
                total_seconds = float(start_time)  # Attempt numeric coercion
            except Exception:
                total_seconds = 0.0  # Fallback to zero
    else:  # Two-argument mode: Compute difference finish_time - start_time
        st = to_seconds(start_time)  # Convert start to seconds if possible
        ft = to_seconds(finish_time)  # Convert finish to seconds if possible
        if st is not None and ft is not None:  # Both converted successfully
            total_seconds = ft - st  # Direct numeric subtraction
        else:  # Fallback to other methods
            try:  # Attempt to subtract (works for datetimes/timedeltas)
                delta = finish_time - start_time  # Try subtracting (works for datetimes/timedeltas)
                total_seconds = float(delta.total_seconds())  # Get seconds from the resulting timedelta
            except Exception:  # Subtraction failed
                try:  # Final attempt: Numeric coercion
                    total_seconds = float(finish_time) - float(start_time)  # Final numeric coercion attempt
                except Exception:  # Numeric coercion failed
                    total_seconds = 0.0  # Fallback to zero on failure

    if total_seconds is None:  # Ensure a numeric value
        total_seconds = 0.0  # Default to zero
    if total_seconds < 0:  # Normalize negative durations
        total_seconds = abs(total_seconds)  # Use absolute value

    days = int(total_seconds // 86400)  # Compute full days
    hours = int((total_seconds % 86400) // 3600)  # Compute remaining hours
    minutes = int((total_seconds % 3600) // 60)  # Compute remaining minutes
    seconds = int(total_seconds % 60)  # Compute remaining seconds

    if days > 0:  # Include days when present
        return f"{days}d {hours}h {minutes}m {seconds}s"  # Return formatted days+hours+minutes+seconds
    if hours > 0:  # Include hours when present
        return f"{hours}h {minutes}m {seconds}s"  # Return formatted hours+minutes+seconds
    if minutes > 0:  # Include minutes when present
        return f"{minutes}m {seconds}s"  # Return formatted minutes+seconds
    return f"{seconds}s"  # Fallback: only seconds


def play_sound():
    """
    Plays a sound when the program finishes and skips if the operating system is Windows.

    :param: None
    :return: None
    """

    current_os = platform.system()  # Get the current operating system
    if current_os == "Windows":  # If the current operating system is Windows
        return  # Do nothing

    if verify_filepath_exists(SOUND_FILE):  # If the sound file exists
        if current_os in SOUND_COMMANDS:  # If the platform.system() is in the SOUND_COMMANDS dictionary
            os.system(f"{SOUND_COMMANDS[current_os]} {SOUND_FILE}")  # Play the sound
        else:  # If the platform.system() is not in the SOUND_COMMANDS dictionary
            print(
                f"{BackgroundColors.RED}The {BackgroundColors.CYAN}{current_os}{BackgroundColors.RED} is not in the {BackgroundColors.CYAN}SOUND_COMMANDS dictionary{BackgroundColors.RED}. Please add it!{Style.RESET_ALL}"
            )
    else:  # If the sound file does not exist
        print(
            f"{BackgroundColors.RED}Sound file {BackgroundColors.CYAN}{SOUND_FILE}{BackgroundColors.RED} not found. Make sure the file exists.{Style.RESET_ALL}"
        )


def main():
    """
    Main function.

    :param: None
    :return: None
    """

    logger.write(
        f"{BackgroundColors.CLEAR_TERMINAL}{BackgroundColors.BOLD}{BackgroundColors.GREEN}Welcome to the {BackgroundColors.CYAN}Media File Integrity Scanner{BackgroundColors.GREEN} program!{Style.RESET_ALL}"
    )  # Output the welcome message
    logger.write("")  # Keep one blank line after the welcome message

    start_time = datetime.datetime.now()  # Get the start time of the program
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)  # Ensure the report output directory exists before processing input roots
    ffmpeg_executable = resolve_ffmpeg_executable()  # Resolve FFmpeg once before starting potentially long media scans
    generated_reports: list[Path] = []  # Store report paths generated successfully during the current program execution
    report_summaries: list[dict[str, int | str | Path]] = []  # Store per-input corruption counts so every report can receive the global summary at the end
    input_failures: list[tuple[str, Exception]] = []  # Store configured input roots that could not be processed

    logger.write(f"{BackgroundColors.GREEN}FFmpeg: {BackgroundColors.CYAN}{unix_path(ffmpeg_executable)}{Style.RESET_ALL}")  # Display the resolved FFmpeg executable used for every integrity scan
    logger.write("")  # Keep one blank line before the first input directory

    for input_dir in INPUT_DIRS:  # Process each configured movie root independently
        try:  # Prevent one unavailable input root from blocking integrity scans for the remaining configured roots
            report_summary = scan_input_directory(ffmpeg_executable, input_dir)  # Scan the complete input root and preserve its generated report metadata
            report_summaries.append(report_summary)  # Store the successful input-root corruption totals for the final cross-input report update
            generated_reports.append(Path(report_summary["report_path"]))  # Preserve the generated JSON report path for terminal summary output
        except Exception as exception:  # Capture input-root configuration or discovery failures
            input_failures.append((input_dir, exception))  # Preserve the failed root and exception for the final program summary
            logger.write(f"{BackgroundColors.RED}Failed input directory: {BackgroundColors.CYAN}{unix_path(input_dir)}{Style.RESET_ALL}")  # Report the input root that could not be processed
            logger.write(f"{BackgroundColors.RED}{type(exception).__name__}: {BackgroundColors.CYAN}{unix_path(str(exception))}{Style.RESET_ALL}")  # Report the concrete input-root failure reason
            logger.write("")  # Keep one blank line after the failed input directory

    update_reports_with_global_corruption_summary(report_summaries)  # Append per-input and global corruption totals to every successfully generated report.
    finish_time = datetime.datetime.now()  # Get the finish time of the program

    print(
        f"{BackgroundColors.GREEN}Generated reports: {BackgroundColors.CYAN}{len(generated_reports)}{BackgroundColors.GREEN} | Failed input directories: {BackgroundColors.CYAN}{len(input_failures)}{Style.RESET_ALL}"
    )  # Output the final report generation totals

    for report_path in generated_reports:  # Display every JSON report successfully produced during the current run
        print(f"{BackgroundColors.GREEN}Report: {BackgroundColors.CYAN}{unix_path(report_path)}{Style.RESET_ALL}")  # Output one generated report path

    print(
        f"{BackgroundColors.GREEN}Start time: {BackgroundColors.CYAN}{start_time.strftime('%d/%m/%Y - %H:%M:%S')}\n{BackgroundColors.GREEN}Finish time: {BackgroundColors.CYAN}{finish_time.strftime('%d/%m/%Y - %H:%M:%S')}\n{BackgroundColors.GREEN}Execution time: {BackgroundColors.CYAN}{calculate_execution_time(start_time, finish_time)}{Style.RESET_ALL}"
    )  # Output the start and finish times

    print(
        f"{BackgroundColors.BOLD}{BackgroundColors.GREEN}Program finished.{Style.RESET_ALL}"
    )  # Output the end of the program message

    (
        atexit.register(play_sound) if RUN_FUNCTIONS["Play Sound"] else None
    )  # Register the play_sound function to be called when the program finishes


if __name__ == "__main__":
    """
    This is the standard boilerplate that calls the main() function.

    :return: None
    """

    main()  # Call the main function
